# 2025-26 Project - Foundations of Computer Science

**Project by:**
- Herandez, Nicole Winy </br>
- Ortega, Azriel Matthew </br>
- Tibayan, Meryann Joy

In [125]:
# import libraries
import pandas as pd
import os
import json

### 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [126]:
# read csv files with read_csv function from pandas
videos_folder = "videos"

df_cavideos = pd.read_csv(f"{videos_folder}/CAvideos.csv")
df_devideos = pd.read_csv(f"{videos_folder}/DEvideos.csv")
df_frvideos = pd.read_csv(f"{videos_folder}/FRvideos.csv")
df_gbvideos = pd.read_csv(f"{videos_folder}/GBvideos.csv")
df_invideos = pd.read_csv(f"{videos_folder}/INvideos.csv")
df_usvideos = pd.read_csv(f"{videos_folder}/USvideos.csv")

# After experimenting, it seems that using default encoding(utf-8) and using encoding errors
# to skip some bytes that cant be read is better than finding a specific encoding for each language
# However, this must be researched more for example: If this only a computer specific problem, or 
# there is a way to read everything properly without having to use encoding errors

df_jpvideos = pd.read_csv(f"{videos_folder}/JPvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_krvideos = pd.read_csv(f"{videos_folder}/KRvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_mxvideos = pd.read_csv(f"{videos_folder}/MXvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_ruvideos = pd.read_csv(f"{videos_folder}/RUvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")

They say it is hard to determine the correct encoding for each text file, especially if it is not utf-8 </br>
Reference https://community.dataquest.io/t/how-do-we-know-the-encoding-to-use-with-pd-read-csv-chardet-doesnt-help/467614/4 </br>

You have to do trial and error with all of the encodings to check which one works best. As for my testing 11/20/2025, utf-8 is best for all with the encoding_errors set to replace.

Here is the docs for checking all encodings : https://docs.python.org/3/library/codecs.html#standard-encodings

In [127]:
# Efficient code version (with concatenation process

# Import all csv files, read and compile them into one dataframe
# With the addition of adding a new column 'country' to determine from what csv file it came from

dataframe_lists = []
for file in os.listdir(videos_folder):
    if file[9:] == "csv":
        print(f"Reading {file}")
        df_temp = pd.read_csv(f"{videos_folder}/{file}", encoding_errors="replace")
        df_temp["country"] = file[:2] # add country column
        dataframe_lists.append(df_temp)

df_videos = pd.concat(dataframe_lists) # concatenate everything into one dataframe
df_videos = df_videos.reset_index(drop=True) # reset index

Reading MXvideos.csv
Reading INvideos.csv
Reading DEvideos.csv
Reading JPvideos.csv
Reading KRvideos.csv
Reading CAvideos.csv
Reading RUvideos.csv
Reading FRvideos.csv
Reading USvideos.csv
Reading GBvideos.csv

In [128]:
df_videos

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...,GB
375938,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...,GB
375939,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...,GB
375940,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...,GB
375941,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...,GB

### 2. Extract all videos that have no tag.

In [129]:
no_tag_videos = df_videos[df_videos["tags"] == "[none]"]
no_tag_videos #all videos

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
5,Q9kK6NWZR1U,17.14.11,Asi se sintio Terremoto en iraq al bordo de ir...,MÚSICA & ENTRETENIMIENTO,10,2017-11-12T20:17:38.000Z,[none],129645,506,67,239,https://i.ytimg.com/vi/Q9kK6NWZR1U/default.jpg,False,False,False,Un fuerte sismo ha afectado en la noche de est...,MX
19,7D-swI6qNLM,17.14.11,HACKS CON SILICÓN CALIENTE,MaireWink,24,2017-11-13T18:00:01.000Z,[none],217025,26934,201,1277,https://i.ytimg.com/vi/7D-swI6qNLM/default.jpg,False,False,False,CANAL DE HISTORIAS:\nhttps://www.youtube.com/H...,MX
25,nEAMm3nGxpM,17.14.11,El valiente ve la muerte solo una vez - Teaser,Agencia Bengala,1,2017-11-13T13:32:23.000Z,[none],7127,37,3,13,https://i.ytimg.com/vi/nEAMm3nGxpM/default.jpg,False,False,False,"A lo largo de su vida, Alejo Garza Tamez ha cu...",MX
38,cgYhR-3QfhM,17.14.11,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,Las Ultimas de HOY,22,2017-11-12T21:00:01.000Z,[none],195613,929,238,92,https://i.ytimg.com/vi/cgYhR-3QfhM/default.jpg,False,False,False,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,MX
56,mevdRfjbwH4,17.14.11,Leslie mar vs Mayela Without you - la voz Méxi...,Pablo Zarate,29,2017-11-13T05:11:11.000Z,[none],15814,91,5,14,https://i.ytimg.com/vi/mevdRfjbwH4/default.jpg,False,False,False,NaN,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375776,1ce456Nnkt8,18.13.06,BABYMETAL - Distortion (OFFICIAL),BABYMETAL,10,2018-05-07T14:59:03.000Z,[none],3371368,92738,2630,9840,https://i.ytimg.com/vi/1ce456Nnkt8/default.jpg,False,False,False,We delivered our new song Distortion as a surp...,GB
375840,fAIX12F6958,18.14.06,Bumblebee (2018) - Official Teaser Trailer - P...,Paramount Pictures,1,2018-06-05T07:00:01.000Z,[none],19864779,228670,16420,46318,https://i.ytimg.com/vi/fAIX12F6958/default.jpg,False,False,False,Every adventure has a beginning. Watch the off...,GB
375851,Y99Wj-NStok,18.14.06,Choco Mountain: The History of Mario Kart 64's...,Summoning Salt,20,2018-06-04T03:24:53.000Z,[none],929926,40563,776,3766,https://i.ytimg.com/vi/Y99Wj-NStok/default.jpg,False,False,False,https://www.twitch.tv/summoningsalthttps://twi...,GB
375910,wswvNZveNHc,18.14.06,Charmed (The CW) Trailer HD - 2018 Reboot,TV Promos,24,2018-05-17T16:07:29.000Z,[none],2201784,35149,16812,12894,https://i.ytimg.com/vi/wswvNZveNHc/default.jpg,False,False,False,"After the tragic death of their mother, three ...",GB
375914,bGW2eZGnznk,18.14.06,THE HAPPYTIME MURDERS Official Trailer (2018),Movie Trailers Source,1,2018-05-18T15:37:16.000Z,[none],607226,4531,715,869,https://i.ytimg.com/vi/bGW2eZGnznk/default.jpg,False,False,False,THE HAPPYTIME MURDERS Official Trailer Action...,GB

In [130]:
no_tag_videos_unici = no_tag_videos.drop_duplicates(subset=["video_id"])
no_tag_videos_unici #unique videos by video_id #there are 23992 unique videos that have no tags

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
5,Q9kK6NWZR1U,17.14.11,Asi se sintio Terremoto en iraq al bordo de ir...,MÚSICA & ENTRETENIMIENTO,10,2017-11-12T20:17:38.000Z,[none],129645,506,67,239,https://i.ytimg.com/vi/Q9kK6NWZR1U/default.jpg,False,False,False,Un fuerte sismo ha afectado en la noche de est...,MX
19,7D-swI6qNLM,17.14.11,HACKS CON SILICÓN CALIENTE,MaireWink,24,2017-11-13T18:00:01.000Z,[none],217025,26934,201,1277,https://i.ytimg.com/vi/7D-swI6qNLM/default.jpg,False,False,False,CANAL DE HISTORIAS:\nhttps://www.youtube.com/H...,MX
25,nEAMm3nGxpM,17.14.11,El valiente ve la muerte solo una vez - Teaser,Agencia Bengala,1,2017-11-13T13:32:23.000Z,[none],7127,37,3,13,https://i.ytimg.com/vi/nEAMm3nGxpM/default.jpg,False,False,False,"A lo largo de su vida, Alejo Garza Tamez ha cu...",MX
38,cgYhR-3QfhM,17.14.11,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,Las Ultimas de HOY,22,2017-11-12T21:00:01.000Z,[none],195613,929,238,92,https://i.ytimg.com/vi/cgYhR-3QfhM/default.jpg,False,False,False,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,MX
56,mevdRfjbwH4,17.14.11,Leslie mar vs Mayela Without you - la voz Méxi...,Pablo Zarate,29,2017-11-13T05:11:11.000Z,[none],15814,91,5,14,https://i.ytimg.com/vi/mevdRfjbwH4/default.jpg,False,False,False,NaN,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372271,H3PKipRZKv0,18.24.05,Is Forces of Destiny good?,Jenny Nicholson,1,2018-05-23T09:04:45.000Z,[none],94868,6712,128,1373,https://i.ytimg.com/vi/H3PKipRZKv0/default.jpg,False,False,False,A pile of colorful beads.Click the next great ...,GB
372437,nyVsiKX8ojQ,18.25.05,Shawn Mendes: The Album - Secret Listening Ses...,Shawn Mendes,10,2018-05-23T22:31:04.000Z,[none],188701,35970,111,2147,https://i.ytimg.com/vi/nyVsiKX8ojQ/default.jpg,False,False,False,Buy and stream Shawn Mendes: The Album at http...,GB
372640,bGW2eZGnznk,18.26.05,THE HAPPYTIME MURDERS Official Trailer (2018),Movie Trailers Source,1,2018-05-18T15:37:16.000Z,[none],312542,3186,450,557,https://i.ytimg.com/vi/bGW2eZGnznk/default.jpg,False,False,False,THE HAPPYTIME MURDERS Official Trailer Action...,GB
374389,1ce456Nnkt8,18.05.06,BABYMETAL - Distortion (OFFICIAL),BABYMETAL,10,2018-05-07T14:59:03.000Z,[none],3104860,89709,2517,9587,https://i.ytimg.com/vi/1ce456Nnkt8/default.jpg,False,False,False,We delivered our new song Distortion as a surp...,GB
374612,Y99Wj-NStok,18.07.06,Choco Mountain: The History of Mario Kart 64's...,Summoning Salt,20,2018-06-04T03:24:53.000Z,[none],600490,29946,468,2931,https://i.ytimg.com/vi/Y99Wj-NStok/default.jpg,False,False,False,https://www.twitch.tv/summoningsalthttps://twi...,GB

### 3. For each channel, determine the total number of views

In [131]:
total_views_per_channel = df_videos.groupby("channel_title")["views"].sum().sort_values(ascending=False)
total_views_per_channel

channel_title
ChildishGambinoVEVO     11016766510
Marvel Entertainment    10430605449
NickyJamTV               9479859505
Ozuna                    8623329509
ibighit                  8205572221
                           ...
NavylittleMonster               365
Videostendencias                302
No Comment TV                   284
Sport Life                      163
Alexander Redking               153
Name: views, Length: 37824, dtype: int64

### 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [132]:
df_videos_disabled = df_videos[df_videos["comments_disabled"] | df_videos["ratings_disabled"] | df_videos["video_error_or_removed"]]
df_videos_disabled

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
7,XzULSsZYMRc,17.14.11,M6.7 Costa Rica Análisis de Terremotos en (((A...,concienciaradio,25,2017-11-13T06:18:23.000Z,"terremoto|""costa rica""|""nicaragua""|""alex backm...",142522,7745,659,0,https://i.ytimg.com/vi/XzULSsZYMRc/default.jpg,True,False,False,"(CR NOTICIAS NOV 12, 2017) UN FUERTE TERREMOTO...",MX
14,Dhhp8M5K3UI,17.14.11,Deleted video,Harrison,24,2017-11-13T04:44:51.000Z,"terremoto costa rica|""Primeras imagenes sismo ...",53265,194,41,90,https://i.ytimg.com/vi/7jmJtdqI6YE/default.jpg,False,False,True,Un sismo de magnitud 6.5 sacudió el domingo po...,MX
32,RkTi5_hu-kY,17.14.11,YURI puso en su lugar a EX TIMBIRICHE en La Vo...,EXPRESS NOTICIAS,24,2017-11-13T14:56:24.000Z,"hoy|""venga la alegria""|""telemundo""|""chismes""|""...",28098,0,0,22,https://i.ytimg.com/vi/RkTi5_hu-kY/default.jpg,False,True,False,¡SUSCRÍBETE!\nEvidentemente nadie podía entend...,MX
88,qxyJYWGf57k,17.14.11,Santa Misa del lunes 13 de noviembre de 2017 (...,Maria de Nazaret,27,2017-11-13T10:31:51.000Z,"Santa misa de hoy|""Santa Misa""|""Misa del dia d...",8010,0,0,0,https://i.ytimg.com/vi/qxyJYWGf57k/default.jpg,True,True,False,→ Suscríbete aquí y sigue la Misa diaria en es...,MX
89,P3q93hzUGEA,17.14.11,Fraudulenta salida de Lis Vega en el Exatlon M...,VIDEOS RANDOM,24,2017-11-12T16:17:41.000Z,"extlon lis vega|""ana lago""|""rommel pacheco""|""h...",21323,0,0,15,https://i.ytimg.com/vi/P3q93hzUGEA/default.jpg,False,True,False,Salida de Lis Vega del Exatlon México 2017 cau...,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375250,pojXEFDFMw8,18.10.06,2018 FIFA World Cup | Forget | ITV,ITV,24,2018-05-11T11:00:09.000Z,"tv|""television""|""ITV""|""Britain""|""British""|""UK""...",369011,4782,483,0,https://i.ytimg.com/vi/pojXEFDFMw8/default.jpg,True,False,False,Join us this summer for the FIFA World Cup 201...,GB
375408,QW8whgmyTNU,18.11.06,This Is America: Women's Edit,Nicole Arbour,24,2018-05-12T22:42:24.000Z,"Nicole Arbour|""World's Sexiest Comedian""|""funn...",3130833,0,0,0,https://i.ytimg.com/vi/QW8whgmyTNU/default.jpg,True,True,False,About This Is America: Women’s EditI thought i...,GB
375581,QW8whgmyTNU,18.12.06,This Is America: Women's Edit,Nicole Arbour,24,2018-05-12T22:42:24.000Z,"Nicole Arbour|""World's Sexiest Comedian""|""funn...",3140732,0,0,0,https://i.ytimg.com/vi/QW8whgmyTNU/default.jpg,True,True,False,About This Is America: Women’s EditI thought i...,GB
375756,QW8whgmyTNU,18.13.06,This Is America: Women's Edit,Nicole Arbour,24,2018-05-12T22:42:24.000Z,"Nicole Arbour|""World's Sexiest Comedian""|""funn...",3149925,0,0,0,https://i.ytimg.com/vi/QW8whgmyTNU/default.jpg,True,True,False,About This Is America: Women’s EditI thought i...,GB
375926,QW8whgmyTNU,18.14.06,This Is America: Women's Edit,Nicole Arbour,24,2018-05-12T22:42:24.000Z,"Nicole Arbour|""World's Sexiest Comedian""|""funn...",3158685,0,0,0,https://i.ytimg.com/vi/QW8whgmyTNU/default.jpg,True,True,False,About This Is America: Women’s EditI thought i...,GB

In [133]:
df_videos = df_videos.drop(df_videos_disabled.index)
df_videos

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...,GB
375938,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...,GB
375939,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...,GB
375940,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...,GB
375941,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...,GB

### 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [134]:
import numpy as np
df_videos["like_ratio"] = df_videos["likes"] / df_videos["dislikes"].replace(0, np.nan)
df_videos[["title", "likes", "dislikes", "like_ratio"]].head(10)

,title,likes,dislikes,like_ratio
0,Capítulo 12 | MasterChef 2017,4182,361,11.584488
1,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,271,174,1.557471
2,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,10105,266,37.988722
3,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,378,171,2.210526
4,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,57781,681,84.847283
5,Asi se sintio Terremoto en iraq al bordo de ir...,506,67,7.552239
6,La Resolana con el Capi | Programa 12 noviembr...,2277,69,33.000000
8,7 Niños Famosos Que No Supieron Adaptarse a La...,20155,912,22.099781
9,TOP: Los 7 libros infantiles más perturbadores...,83582,2194,38.095716
10,Franco Escamilla.- Tradiciones y Faitelson,23279,270,86.218519

In [135]:
# if needed: how many rows have like_ratio = NaN
num_nan_ratio = df_videos["like_ratio"].isna().sum()
print("Righe con like_ratio NaN:", num_nan_ratio)

# rows with like_ratio NaN
ratio_nan_rows = df_videos[df_videos["like_ratio"].isna()]
ratio_nan_rows.head(5)

Righe con like_ratio NaN: 2390

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio
120,vl8yv7kTTWI,17.14.11,Budín de zanahoria - Cocina Vegan Fácil,Cocina Vegan fácil,24,2017-11-13T14:00:03.000Z,"budín|""zanahoria""|""budín de zanahoria""|""budín ...",5113,823,0,190,https://i.ytimg.com/vi/vl8yv7kTTWI/default.jpg,False,False,False,"Hoy tenemos un delicioso postre vegano, budín ...",MX,NaN
188,MGeSKdq1V20,17.14.11,Iraqi Kurdistan Earthquake live during an inte...,Ahmed Nasradin,22,2017-11-12T19:44:05.000Z,[none],3033,12,0,0,https://i.ytimg.com/vi/MGeSKdq1V20/default.jpg,False,False,False,"An Earthquake hit iraq with 7.2 Magnitude , st...",MX,NaN
194,_0FiEmKkIHU,17.14.11,TERREMOTO 6.5 EN COSTA RICA 12/11/2017,ElJuanjoSabe,25,2017-11-13T05:25:05.000Z,"TERREMOTO|""TERREMOTO EN COSTA RICA""|""COSTA RIC...",6481,20,0,2,https://i.ytimg.com/vi/_0FiEmKkIHU/default.jpg,False,False,False,"n sismo de magnitud 6,5 ha sacudido este domin...",MX,NaN
303,AWqYXzvT4OM,17.15.11,Transmisión en vivo del LXXIII Congreso y Camp...,"Federación Mexicana de Charrería, A.C.",17,2017-11-14T22:53:18.000Z,"Charrería|""Charros""|""México""|""Hidalgo""|""Pachuc...",3874,17,0,0,https://i.ytimg.com/vi/AWqYXzvT4OM/default.jpg,False,False,False,"En vivo desde el lienzo charro Hidalgo, Cuna d...",MX,NaN
384,dqMGDmIIusg,17.15.11,Caer en tentación: Mía descubre la verdad | Es...,Las Estrellas,24,2017-11-15T04:30:00.000Z,"Televisa|""Telenovela""|""Soap Opera""|""Las Estrel...",3147,55,0,10,https://i.ytimg.com/vi/dqMGDmIIusg/default.jpg,False,False,False,Damian y Carolina son descubiertos por Mía. El...,MX,NaN

### 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [136]:
pt = pd.to_datetime(df_videos["publish_time"], utc=True, errors="coerce")
start = pt.dt.floor("10min")
df_videos["publish_interval"] = (
    start.dt.strftime("%H:%M") + " - " +
    (start + pd.Timedelta(minutes=10)).dt.strftime("%H:%M")
)

df_videos[["publish_time", "publish_interval"]]

                    publish_time publish_interval
0       2017-11-13T06:06:22.000Z    06:00 - 06:10
1       2017-11-13T05:11:58.000Z    05:10 - 05:20
2       2017-11-13T17:00:02.000Z    17:00 - 17:10
3       2017-11-13T03:47:10.000Z    03:40 - 03:50
4       2017-11-13T19:17:48.000Z    19:10 - 19:20
...                          ...              ...
375937  2018-05-09T07:00:01.000Z    07:00 - 07:10
375938  2018-05-11T17:09:16.000Z    17:00 - 17:10
375939  2018-05-08T11:05:08.000Z    11:00 - 11:10
375940  2018-05-08T20:32:32.000Z    20:30 - 20:40
375941  2018-05-11T04:06:35.000Z    04:00 - 04:10

[362285 rows x 2 columns]

### 7. For each interval, determine the number of videos, average number of likes and of dislikes.

In [137]:
# Unique Videos

interval_stats = df_videos.groupby("publish_interval").agg(
    number_of_videos = ("video_id", "nunique"),
    average_likes = ("likes", "mean"),
    average_dislikes = ("dislikes", "mean")
)

interval_stats.sort_index().head(50)

                  number_of_videos  average_likes  average_dislikes
publish_interval
00:00 - 00:10                 1329   62819.249823       3902.800425
00:10 - 00:20                  717   20898.900281       1448.770365
00:20 - 00:30                  617   22120.714762       1109.575480
00:30 - 00:40                  807   38038.324342        981.208735
00:40 - 00:50                  605   43956.824979       1988.883320
00:50 - 01:00                  648   38477.080031       1624.353535
01:00 - 01:10                 1285   16279.507786        755.636156
01:10 - 01:20                  659  111360.698713       6188.202877
01:20 - 01:30                  638   26478.148465       1794.689507
01:30 - 01:40                  789   14158.308609       6303.031788
01:40 - 01:50                  659   27553.537260       1554.941803
01:50 - 02:00                  582   22758.016304       3011.490683
02:00 - 02:10                 1206   15009.802626        712.445682
02:10 - 02:20                  713   36820.814237       1411.413559
02:20 - 02:30                  680    9256.550628        648.410042
02:30 - 02:40                  958   11688.613904        540.015508
02:40 - 02:50                  699   48906.661940       1516.273134
02:50 - 03:00                  746   14997.880249        617.956454
03:00 - 03:10                 1563   22056.764942        947.730885
03:10 - 03:20                  803    9970.889853        764.847797
03:20 - 03:30                  683    7524.439044        663.503586
03:30 - 03:40                  948   39773.712375       1850.771620
03:40 - 03:50                  661   70424.588554       2418.658159
03:50 - 04:00                  600   33226.223759       1835.115541
04:00 - 04:10                 1251  222450.323980       9968.693112
04:10 - 04:20                  572   26520.408063       1886.887906
04:20 - 04:30                  620   18133.211790        785.309316
04:30 - 04:40                 1019   33052.861926       1382.933857
04:40 - 04:50                  602   72456.546185       2604.184739
04:50 - 05:00                  589   38646.406657       3298.701881
05:00 - 05:10                 1509  159030.767039       5999.943603
05:10 - 05:20                  579    8641.205516        592.339858
05:20 - 05:30                  608   17651.564885        968.045038
05:30 - 05:40                  848   25118.492029       2093.479934
05:40 - 05:50                  617   27636.837971       1770.430442
05:50 - 06:00                  526   15764.073194        680.259506
06:00 - 06:10                 1251   14450.201862       1131.004232
06:10 - 06:20                  543   14144.686069        655.333969
06:20 - 06:30                  591   20387.539474       2261.495066
06:30 - 06:40                  856   18912.380952       1182.281838
06:40 - 06:50                  564   17157.132607        940.502271
06:50 - 07:00                  561   28623.361134       1674.197665
07:00 - 07:10                 1672   29120.583139       1582.834597
07:10 - 07:20                  625   11537.661959        681.376648
07:20 - 07:30                  649    7082.685739        732.335611
07:30 - 07:40                  947   17656.652559       1207.000000
07:40 - 07:50                  632    8831.133036        680.457143
07:50 - 08:00                  648   53404.147298       2249.116210
08:00 - 08:10                 2053   21111.330892       1029.571609
08:10 - 08:20                  727   29839.862509        956.857250

In [138]:
# By Rows
interval_stats = df_videos.groupby("publish_interval").agg(
    number_of_videos = ("video_id", "count"),
    average_likes = ("likes", "mean"),
    average_dislikes = ("dislikes", "mean")
)

interval_stats.sort_index().head(50)

                  number_of_videos  average_likes  average_dislikes
publish_interval
00:00 - 00:10                 2826   62819.249823       3902.800425
00:10 - 00:20                 1424   20898.900281       1448.770365
00:20 - 00:30                 1199   22120.714762       1109.575480
00:30 - 00:40                 1557   38038.324342        981.208735
00:40 - 00:50                 1217   43956.824979       1988.883320
00:50 - 01:00                 1287   38477.080031       1624.353535
01:00 - 01:10                 2633   16279.507786        755.636156
01:10 - 01:20                 1321  111360.698713       6188.202877
01:20 - 01:30                 1401   26478.148465       1794.689507
01:30 - 01:40                 1510   14158.308609       6303.031788
01:40 - 01:50                 1409   27553.537260       1554.941803
01:50 - 02:00                 1288   22758.016304       3011.490683
02:00 - 02:10                 2513   15009.802626        712.445682
02:10 - 02:20                 1475   36820.814237       1411.413559
02:20 - 02:30                 1195    9256.550628        648.410042
02:30 - 02:40                 1870   11688.613904        540.015508
02:40 - 02:50                 1340   48906.661940       1516.273134
02:50 - 03:00                 1286   14997.880249        617.956454
03:00 - 03:10                 2995   22056.764942        947.730885
03:10 - 03:20                 1498    9970.889853        764.847797
03:20 - 03:30                 1255    7524.439044        663.503586
03:30 - 03:40                 2093   39773.712375       1850.771620
03:40 - 03:50                 1293   70424.588554       2418.658159
03:50 - 04:00                 1229   33226.223759       1835.115541
04:00 - 04:10                 3920  222450.323980       9968.693112
04:10 - 04:20                 1017   26520.408063       1886.887906
04:20 - 04:30                 1374   18133.211790        785.309316
04:30 - 04:40                 2419   33052.861926       1382.933857
04:40 - 04:50                 1245   72456.546185       2604.184739
04:50 - 05:00                 1382   38646.406657       3298.701881
05:00 - 05:10                 5018  159030.767039       5999.943603
05:10 - 05:20                 1124    8641.205516        592.339858
05:20 - 05:30                 1310   17651.564885        968.045038
05:30 - 05:40                 1819   25118.492029       2093.479934
05:40 - 05:50                 1222   27636.837971       1770.430442
05:50 - 06:00                 1052   15764.073194        680.259506
06:00 - 06:10                 2363   14450.201862       1131.004232
06:10 - 06:20                 1048   14144.686069        655.333969
06:20 - 06:30                 1216   20387.539474       2261.495066
06:30 - 06:40                 1806   18912.380952       1182.281838
06:40 - 06:50                 1101   17157.132607        940.502271
06:50 - 07:00                 1199   28623.361134       1674.197665
07:00 - 07:10                 3428   29120.583139       1582.834597
07:10 - 07:20                 1062   11537.661959        681.376648
07:20 - 07:30                 1171    7082.685739        732.335611
07:30 - 07:40                 2032   17656.652559       1207.000000
07:40 - 07:50                 1120    8831.133036        680.457143
07:50 - 08:00                 1351   53404.147298       2249.116210
08:00 - 08:10                 3959   21111.330892       1029.571609
08:10 - 08:20                 1331   29839.862509        956.857250

### 8. For each tag, determine the number of videos. Notice that tags contains a string with several tags

Setup tag column in our dataframe first <br>
Split the string into array with '|' as the separator <br>

Explode dataframe so that each row wiill have one tag, it will duplicate rows with many tags. This is the approach because it is useful when grouping by tags.

In [139]:
df_videos_tags = df_videos.copy()

In [140]:
df_videos_tags["tags"] = df_videos_tags["tags"].str.split('|')

In [141]:
df_videos_tags = df_videos_tags[["video_id", "tags", "like_ratio", "country", "trending_date"]]

In [142]:
df_videos_tags_explode = df_videos_tags.explode('tags')

In [143]:
# clean dataset by removing all extra characters such as double quotations (")
df_videos_tags_explode["tags"] = df_videos_tags_explode["tags"].str.replace('"', '').str.strip()

In [144]:
df_videos_tags_explode = df_videos_tags_explode[df_videos_tags_explode['tags'].str.strip() != ""]

In [145]:
# Videos with no tags are excluded
df_videos_tags_explode.groupby(by="tags")['video_id'].nunique()

tags
! Banii i-au luat mintile                          2
!!                                                 5
!! *me bloquea*                                    1
!!!                                                1
!!!!                                               2
                                                  ..
😜😜                                                 1
😥                                                  1
😭 #résistancelamaindesqueezie ❤️                   1
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية    1
🤝 ZARBEX zahlt Schutzgeld!!!                       1
Name: video_id, Length: 831130, dtype: int64

In [146]:
# Number of videos with no tags (if needed)
df_videos_tags_explode[df_videos_tags_explode["tags"] == "[none]"]["video_id"].nunique()

22580

### 9. Find the tags with the largest number of videos

In [147]:
df_videos_tags_explode[df_videos_tags_explode["tags"] != "[none]"].groupby(by="tags")['video_id'].nunique().sort_values(ascending=False).head(1)

tags
2018    5524
Name: video_id, dtype: int64

### 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [148]:
df_videos_tags_only = df_videos_tags_explode[(df_videos_tags_explode["tags"] != "[none]")]

In [149]:
pd.DataFrame(df_videos_tags_only.groupby(by=["tags","country"])["like_ratio"].mean())

                                                         like_ratio
tags                                            country
! Banii i-au luat mintile                       DE         6.222739
!!                                              FR        12.452875
                                                MX        38.081559
!! *me bloquea*                                 MX        65.260870
!!!                                             MX        12.952381
...                                                             ...
😜😜                                              RU         7.203704
😥                                               DE        26.384615
😭 #résistancelamaindesqueezie ❤️                FR        10.219048
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية FR         6.223873
🤝 ZARBEX zahlt Schutzgeld!!!                    DE        13.989691

[1076212 rows x 1 columns]

### 11. For each (trending_date, country) pair, the video with the largest number of views

In [150]:
max_views = df_videos.groupby(["trending_date", "country"])["views"].transform("max")
max_views

0          4477587
1          4477587
2          4477587
3          4477587
4          4477587
            ...
375937    94254507
375938    94254507
375939    94254507
375940    94254507
375941    94254507
Name: views, Length: 362285, dtype: int64

In [151]:
max_views = df_videos.groupby(["trending_date", "country"])["views"].transform("max")
df_videos_group = df_videos[df_videos["views"] == max_views]

In [152]:
# Sort columns, to display Country, Trending Date and then Views First.
priority_columns = ["trending_date","country", "views"]
other_columns = [col for col in df_videos.columns if col not in priority_columns]

df_videos_group[priority_columns + other_columns]

,trending_date,country,views,video_id,title,channel_title,category_id,publish_time,tags,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,like_ratio,publish_interval
177,17.14.11,MX,4477587,JzCsM1vtn78,THE LOGANG MADE HISTORY. LOL. AGAIN.,Logan Paul Vlogs,24,2017-11-12T20:19:24.000Z,"logan paul vlog|""logan paul""|""logan""|""paul""|""o...",292841,4124,36391,https://i.ytimg.com/vi/JzCsM1vtn78/default.jpg,False,False,False,Join the movement. Be a Maverick ► https://Sho...,71.008972,20:10 - 20:20
267,17.15.11,MX,2765121,VsYmwBOYfW8,Mean Tweets – Jimmy Kimmel Edition,Jimmy Kimmel Live,23,2017-11-14T08:30:01.000Z,"jimmy|""jimmy kimmel""|""jimmy kimmel live""|""late...",35532,1705,2388,https://i.ytimg.com/vi/VsYmwBOYfW8/default.jpg,False,False,False,"In honor of Jimmy’s 50th birthday, we surprise...",20.839883,08:30 - 08:40
402,17.16.11,MX,3979891,8-Cjsnq8kVU,Deadpool’s “Wet on Wet” Teaser,20th Century Fox,1,2017-11-15T14:01:03.000Z,"Trailer|""Deadpool""|""20th Century Fox (Producti...",151855,2378,8079,https://i.ytimg.com/vi/8-Cjsnq8kVU/default.jpg,False,False,False,"After surviving a near fatal bovine attack, a ...",63.858284,14:00 - 14:10
618,17.17.11,MX,6659676,8-Cjsnq8kVU,Deadpool’s “Wet on Wet” Teaser,20th Century Fox,1,2017-11-15T14:01:03.000Z,"Trailer|""Deadpool""|""20th Century Fox (Producti...",223824,4516,11792,https://i.ytimg.com/vi/8-Cjsnq8kVU/default.jpg,False,False,False,"After surviving a near fatal bovine attack, a ...",49.562445,14:00 - 14:10
812,17.18.11,MX,18558186,TyHvyGVs42U,"Luis Fonsi, Demi Lovato - Échame La Culpa",LuisFonsiVEVO,10,2017-11-17T05:00:01.000Z,"Luis|""Fonsi""|""Demi""|""Lovato""|""Échame""|""La""|""Cu...",1002598,32181,59945,https://i.ytimg.com/vi/TyHvyGVs42U/default.jpg,False,False,False,“Échame La Culpa” disponible ya en todas las p...,31.154967,05:00 - 05:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375261,18.10.06,GB,258282383,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06T04:00:07.000Z,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",5426274,378503,551747,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...,14.336145,04:00 - 04:10
375427,18.11.06,GB,259721696,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06T04:00:07.000Z,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",5444541,379862,553371,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...,14.332945,04:00 - 04:10
375509,18.12.06,GB,85159766,xTlNMmZKwpA,"Cardi B, Bad Bunny & J Balvin - I Like It [Off...",Cardi B,10,2018-05-29T14:05:10.000Z,"Cardi B|""I Like It""|""Invasion of Privacy""|""Bad...",1747201,97897,98163,https://i.ytimg.com/vi/xTlNMmZKwpA/default.jpg,False,False,False,"Cardi B, Bad Bunny & J Balvin - I Like It from...",17.847340,14:00 - 14:10
375688,18.13.06,GB,89740876,xTlNMmZKwpA,"Cardi B, Bad Bunny & J Balvin - I Like It [Off...",Cardi B,10,2018-05-29T14:05:10.000Z,"Cardi B|""I Like It""|""Invasion of Privacy""|""Bad...",1782646,100240,99772,https://i.ytimg.com/vi/xTlNMmZKwpA/default.jpg,False,False,False,"Cardi B, Bad Bunny & J Balvin - I Like It from...",17.783779,14:00 - 14:10
375863,18.14.06,GB,94254507,xTlNMmZKwpA,"Cardi B, Bad Bunny & J Balvin - I Like It [Off...",Cardi B,10,2018-05-29T14:05:10.000Z,"Cardi B|""I Like It""|""Invasion of Privacy""|""Bad...",1816753,102474,101077,https://i.ytimg.com/vi/xTlNMmZKwpA/default.jpg,False,False,False,"Cardi B, Bad Bunny & J Balvin - I Like It from...",17.728917,14:00 - 14:10

### 12. Divide trending_date into three columns: year, month, day

In [153]:
df_videos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 362285 entries, 0 to 375941
Data columns (total 19 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   video_id                362285 non-null  object
 1   trending_date           362285 non-null  object
 2   title                   362285 non-null  object
 3   channel_title           362285 non-null  object
 4   category_id             362285 non-null  int64
 5   publish_time            362285 non-null  object
 6   tags                    362285 non-null  object
 7   views                   362285 non-null  int64
 8   likes                   362285 non-null  int64
 9   dislikes                362285 non-null  int64
 10  comment_count           362285 non-null  int64
 11  thumbnail_link          362285 non-null  object
 12  comments_disabled       362285 non-null  bool
 13  ratings_disabled        362285 non-null  bool
 14  video_error_or_removed  362285 non-null  bool
 15  description             344044 non-null  object
 16  country                 362285 non-null  object
 17  like_ratio              359895 non-null  float64
 18  publish_interval        362285 non-null  object
dtypes: bool(3), float64(1), int64(5), object(10)
memory usage: 48.0+ MB

In [154]:
df_videos['trending_date'] = pd.to_datetime(df_videos['trending_date'], format='%y.%d.%m')

df_videos['year'] = df_videos['trending_date'].dt.year
df_videos['month'] = df_videos['trending_date'].dt.month
df_videos['day'] = df_videos['trending_date'].dt.day

print(df_videos[['trending_date', 'year', 'month', 'day']].head())

  trending_date  year  month  day
0    2017-11-14  2017     11   14
1    2017-11-14  2017     11   14
2    2017-11-14  2017     11   14
3    2017-11-14  2017     11   14
4    2017-11-14  2017     11   14

### 13. For each (month, country) pair, the video with the largest number of views

In [155]:
max_views_indices = df_videos.groupby(['month', 'country'])['views'].idxmax()

df_max_views = df_videos.loc[max_views_indices]

df_max_views

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval,year,month,day
184947,LsoLEjrDogU,2018-01-09,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04T04:49:43.000Z,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",43067983,1717177,61567,...,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,CA,27.891192,04:40 - 04:50,2018,1,9
88852,LsoLEjrDogU,2018-01-08,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04T04:49:43.000Z,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",37728802,1629946,56305,...,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,DE,28.948513,04:40 - 04:50,2018,1,8
266485,LsoLEjrDogU,2018-01-08,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04T04:49:43.000Z,"Bruno Mars""|""Finesse""|""Cardi B""|""Finesse Remix...",37728802,1629948,56305,...,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,FR,28.948548,04:40 - 04:50,2018,1,8
349789,LsoLEjrDogU,2018-01-18,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04T04:49:43.000Z,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",90598955,2248693,93089,...,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,GB,24.156377,04:40 - 04:50,2018,1,18
52495,dfnCAmr569k,2018-01-18,"Taylor Swift - End Game ft. Ed Sheeran, Future",TaylorSwiftVEVO,10,2018-01-12T05:00:01.000Z,"Taylor|""Swift""|""End""|""Game""|""Big""|""Machine""|""Pop""",42019590,1804377,100033,...,False,False,False,Music video by Taylor Swift performing End Gam...,IN,18.037818,05:00 - 05:10,2018,1,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45859,FlsCjmMhFmw,2017-12-12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",125432237,2912710,1545017,...,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",IN,1.885228,17:50 - 18:00,2017,12,12
144022,FlsCjmMhFmw,2017-12-11,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",113876217,2811223,1470388,...,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",KR,1.911892,17:50 - 18:00,2017,12,11
5261,FlsCjmMhFmw,2017-12-10,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",100912384,2656698,1353667,...,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",MX,1.962593,17:50 - 18:00,2017,12,10
219447,FlsCjmMhFmw,2017-12-08,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",52611730,1891836,884967,...,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",RU,2.137748,17:50 - 18:00,2017,12,8
302258,FlsCjmMhFmw,2017-12-14,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",149376127,3093544,1643059,...,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",US,1.882795,17:50 - 18:00,2017,12,14

### 14. Read all json files with the video categories

In [156]:
json_folder = 'categories'
df_list = []

for file in os.listdir(json_folder):
    if file.endswith(".json"):
        country_code = file.split('_')[0] 
        
        with open(os.path.join(json_folder, file), 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        df_temp = pd.json_normalize(data['items'])
        df_temp['id'] = df_temp['id'].astype(int)
        df_temp['country'] = country_code
        df_list.append(df_temp)

df_categories = pd.concat(df_list, ignore_index=True)

df_categories

,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable,country
0,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True,IN
1,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True,IN
2,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True,IN
3,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True,IN
4,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True,IN
...,...,...,...,...,...,...,...
306,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/N1TrDFLRppxZgBowC...",40,UCBR8-60-B28hp2BmDPdntcQ,Sci-Fi/Fantasy,False,DE
307,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/7UMGi6zRySqXopr_r...",41,UCBR8-60-B28hp2BmDPdntcQ,Thriller,False,DE
308,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/RScXhi324h8usyIet...",42,UCBR8-60-B28hp2BmDPdntcQ,Shorts,False,DE
309,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiG...",43,UCBR8-60-B28hp2BmDPdntcQ,Shows,False,DE
310,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/x5NxSf5fz8hn4loSN...",44,UCBR8-60-B28hp2BmDPdntcQ,Trailers,False,DE

### 15. For each country, determine how many videos have a category that is not assignable

In [157]:
df_merged = pd.merge(df_videos, df_categories, left_on = ['country', 'category_id'], right_on = ['country', 'id'],how='left')
df_merged.shape
df_merged

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,publish_interval,year,month,day,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable
0,SbOwzAl9ZfQ,2017-11-14,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,...,06:00 - 06:10,2017,11,14,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/UVB9oxX2Bvqa_w_y3...",24.0,UCBR8-60-B28hp2BmDPdntcQ,Entertainment,True
1,klOV6Xh-DnI,2017-11-14,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,...,05:10 - 05:20,2017,11,14,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/xId8RX7vRN8rqkbYZ...",22.0,UCBR8-60-B28hp2BmDPdntcQ,People & Blogs,True
2,6L2ZF7Qzsbk,2017-11-14,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,...,17:00 - 17:10,2017,11,14,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/QiLK0ZIrFoORdk_g2...",25.0,UCBR8-60-B28hp2BmDPdntcQ,News & Politics,True
3,hcY52MFWMDM,2017-11-14,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,...,03:40 - 03:50,2017,11,14,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/QiLK0ZIrFoORdk_g2...",25.0,UCBR8-60-B28hp2BmDPdntcQ,News & Politics,True
4,_OXDcGPVAa4,2017-11-14,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,...,19:10 - 19:20,2017,11,14,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/r6Ck6Z0_L0rG37VJQ...",26.0,UCBR8-60-B28hp2BmDPdntcQ,Howto & Style,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362280,l884wKofd54,2018-06-14,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,...,07:00 - 07:10,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/nqRIq97-xe5XRZTxb...",10.0,UCBR8-60-B28hp2BmDPdntcQ,Music,True
362281,IP8k2xkhOdI,2018-06-14,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,...,17:00 - 17:10,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/nqRIq97-xe5XRZTxb...",10.0,UCBR8-60-B28hp2BmDPdntcQ,Music,True
362282,Il-an3K9pjg,2018-06-14,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,...,11:00 - 11:10,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/nqRIq97-xe5XRZTxb...",10.0,UCBR8-60-B28hp2BmDPdntcQ,Music,True
362283,-DRsfNObKIQ,2018-06-14,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,...,20:30 - 20:40,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/UVB9oxX2Bvqa_w_y3...",24.0,UCBR8-60-B28hp2BmDPdntcQ,Entertainment,True
362284,4YFo4bdMO8Q,2018-06-14,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,...,04:00 - 04:10,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/nqRIq97-xe5XRZTxb...",10.0,UCBR8-60-B28hp2BmDPdntcQ,Music,True

In [158]:
# Videos where category information is missing (assignable is NaN)
missing_info = df_merged[df_merged['snippet.assignable'].isna()]
missing_info[['video_id','category_id','country','snippet.assignable']]

           video_id  category_id country snippet.assignable
53      mevdRfjbwH4           29      MX                NaN
58      M4W-nrYGRYc           29      MX                NaN
226     Lz58Ch1VnR8           29      MX                NaN
382     o6Qj8FgmgXU           29      MX                NaN
512     o6Qj8FgmgXU           29      MX                NaN
...             ...          ...     ...                ...
358963  p1DAEZNyJ8E           29      GB                NaN
359132  p1DAEZNyJ8E           29      GB                NaN
359301  p1DAEZNyJ8E           29      GB                NaN
359468  p1DAEZNyJ8E           29      GB                NaN
359631  p1DAEZNyJ8E           29      GB                NaN

[2261 rows x 4 columns]

In [159]:
#Missing categories in JSON files for each country
missing_categories_by_country = (
    df_merged[df_merged['snippet.assignable'].isna()]
    .groupby('country')
    ['category_id'].unique() 
    .reset_index(name='missing_category_id')
)

print(missing_categories_by_country)

  country missing_category_id
0      CA                [29]
1      DE                [29]
2      FR                [29]
3      GB                [29]
4      IN                [29]
5      JP                [29]
6      KR                [29]
7      MX                [29]
8      RU                [29]

In [160]:
#video count for each country where assignable is NaN
df_Nan_assignable = (
    df_merged[df_merged['snippet.assignable'].isna()]
    .groupby('country')
    ['video_id'].nunique()
    .reset_index(name='nan_assignable_count')
    .sort_values('nan_assignable_count', ascending=False)
)

print(df_Nan_assignable)

  country  nan_assignable_count
8      RU                  1089
1      DE                   180
7      MX                   125
6      KR                   114
2      FR                    78
0      CA                    47
4      IN                    28
5      JP                    13
3      GB                     6

In [161]:
# count of unique videos that are not assignable for each country, including those with NaN assignable
df_Nan_not_assignable = (df_merged[(df_merged['snippet.assignable'] == False) | (df_merged['snippet.assignable'].isna())]
    .groupby('country')
    ['video_id'].nunique()
    .reset_index(name='Nan_non_assignable_count')
    .sort_values('Nan_non_assignable_count', ascending = False) 
)

df_Nan_not_assignable

  country  Nan_non_assignable_count
8      RU                      1244
1      DE                       277
6      KR                       188
2      FR                       184
0      CA                       158
4      IN                       151
7      MX                       128
5      JP                        13
3      GB                         7
9      US                         4

In [162]:
#videos that are not assignable for each country
df_non_assignable = (df_merged[df_merged['snippet.assignable'] == False]
    .groupby('country')
    ['video_id'].nunique()
    .reset_index(name='non_assignable_count')
    .sort_values('non_assignable_count', ascending = False)
)

df_non_assignable

  country  non_assignable_count
7      RU                   158
4      IN                   123
0      CA                   111
2      FR                   106
1      DE                    97
5      KR                    75
8      US                     4
6      MX                     3
3      GB                     1