# 2025-26 Project - Foundations of Computer Science

**Project by:**
- Herandez, Nicole Winy </br>
- Ortega, Azriel Matthew </br>
- Tibayan, Meryann Joy

In [1]:
# import libraries
import pandas as pd
import os
import json

### 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [2]:
# read csv files with read_csv function from pandas
videos_folder = "videos"

df_cavideos = pd.read_csv(f"{videos_folder}/CAvideos.csv")
df_devideos = pd.read_csv(f"{videos_folder}/DEvideos.csv")
df_frvideos = pd.read_csv(f"{videos_folder}/FRvideos.csv")
df_gbvideos = pd.read_csv(f"{videos_folder}/GBvideos.csv")
df_invideos = pd.read_csv(f"{videos_folder}/INvideos.csv")
df_usvideos = pd.read_csv(f"{videos_folder}/USvideos.csv")

# After experimenting, it seems that using default encoding(utf-8) and using encoding errors
# to skip some bytes that cant be read is better than finding a specific encoding for each language
# However, this must be researched more for example: If this only a computer specific problem, or 
# there is a way to read everything properly without having to use encoding errors

df_jpvideos = pd.read_csv(f"{videos_folder}/JPvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_krvideos = pd.read_csv(f"{videos_folder}/KRvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_mxvideos = pd.read_csv(f"{videos_folder}/MXvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_ruvideos = pd.read_csv(f"{videos_folder}/RUvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")

They say it is hard to determine the correct encoding for each text file, especially if it is not utf-8 </br>
Reference https://community.dataquest.io/t/how-do-we-know-the-encoding-to-use-with-pd-read-csv-chardet-doesnt-help/467614/4 </br>

You have to do trial and error with all of the encodings to check which one works best. As for my testing 11/20/2025, utf-8 is best for all with the encoding_errors set to replace.

Here is the docs for checking all encodings : https://docs.python.org/3/library/codecs.html#standard-encodings

In [3]:
# Efficient code version (with concatenation process

# Import all csv files, read and compile them into one dataframe
# With the addition of adding a new column 'country' to determine from what csv file it came from

dataframe_lists = []
for file in os.listdir(videos_folder):
    if file[9:] == "csv":
        print(f"Reading {file}")
        df_temp = pd.read_csv(f"{videos_folder}/{file}", encoding_errors="replace")
        df_temp["country"] = file[:2] # add country column
        dataframe_lists.append(df_temp)

df_videos = pd.concat(dataframe_lists) # concatenate everything into one dataframe
df_videos = df_videos.reset_index(drop=True) # reset index

Reading MXvideos.csv
Reading DEvideos.csv
Reading FRvideos.csv
Reading INvideos.csv
Reading RUvideos.csv
Reading JPvideos.csv
Reading GBvideos.csv
Reading KRvideos.csv
Reading CAvideos.csv
Reading USvideos.csv

In [4]:
df_videos

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

### 2. Extract all videos that have no tag.

 I extracted videos with no tags by cleaning the tags column first: I handled nulls, converted values to strings, trimmed spaces, and normalized case. Then I filtered values like [none], none, empty string.

In [5]:
no_tag_videos = df_videos[df_videos["tags"].fillna("").astype(str).str.strip().str.lower().isin(["[none]", "none", "", "nan", "null"])]
no_tag_videos #print all videos that have tags [none]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
5,Q9kK6NWZR1U,17.14.11,Asi se sintio Terremoto en iraq al bordo de ir...,MÚSICA & ENTRETENIMIENTO,10,2017-11-12T20:17:38.000Z,[none],129645,506,67,239,https://i.ytimg.com/vi/Q9kK6NWZR1U/default.jpg,False,False,False,Un fuerte sismo ha afectado en la noche de est...,MX
19,7D-swI6qNLM,17.14.11,HACKS CON SILICÓN CALIENTE,MaireWink,24,2017-11-13T18:00:01.000Z,[none],217025,26934,201,1277,https://i.ytimg.com/vi/7D-swI6qNLM/default.jpg,False,False,False,CANAL DE HISTORIAS:\nhttps://www.youtube.com/H...,MX
25,nEAMm3nGxpM,17.14.11,El valiente ve la muerte solo una vez - Teaser,Agencia Bengala,1,2017-11-13T13:32:23.000Z,[none],7127,37,3,13,https://i.ytimg.com/vi/nEAMm3nGxpM/default.jpg,False,False,False,"A lo largo de su vida, Alejo Garza Tamez ha cu...",MX
38,cgYhR-3QfhM,17.14.11,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,Las Ultimas de HOY,22,2017-11-12T21:00:01.000Z,[none],195613,929,238,92,https://i.ytimg.com/vi/cgYhR-3QfhM/default.jpg,False,False,False,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,MX
56,mevdRfjbwH4,17.14.11,Leslie mar vs Mayela Without you - la voz Méxi...,Pablo Zarate,29,2017-11-13T05:11:11.000Z,[none],15814,91,5,14,https://i.ytimg.com/vi/mevdRfjbwH4/default.jpg,False,False,False,NaN,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375815,VGykknw9eCM,18.14.06,"Made Defiant: The Mixtape ft. Neymar Jr., Kane...",Beats by Dre,10,2018-06-07T07:01:06.000Z,[none],3577614,12318,1345,1414,https://i.ytimg.com/vi/VGykknw9eCM/default.jpg,False,False,False,"When your time comes, you have two choices. Yo...",US
375819,fAIX12F6958,18.14.06,Bumblebee (2018) - Official Teaser Trailer - P...,Paramount Pictures,1,2018-06-05T07:00:01.000Z,[none],19864779,228670,16420,46318,https://i.ytimg.com/vi/fAIX12F6958/default.jpg,False,False,False,Every adventure has a beginning. Watch the off...,US
375865,gS1DbvHHVH0,18.14.06,Going in to brain surgery,Simone Giertz,28,2018-05-30T14:22:13.000Z,[none],1635301,120791,1098,20711,https://i.ytimg.com/vi/gS1DbvHHVH0/default.jpg,False,False,False,We’ll post an update on Instagram and Twitter ...,US
375873,E4c7EE8_IX0,18.14.06,Weezer - Africa,weezer,10,2018-05-29T12:00:11.000Z,[none],4682557,115240,5069,9170,https://i.ytimg.com/vi/E4c7EE8_IX0/default.jpg,False,False,False,Stream + download the song: http://fanlink.to/...,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,THE HAPPYTIME MURDERS Official Trailer Action...,GB

I also created a deduplicated version by video_id to count unique videos.

In [6]:
no_tag_videos_unici = no_tag_videos.drop_duplicates(subset=["video_id"])
no_tag_videos_unici #there are 23992 unique videos that have tags [none]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
5,Q9kK6NWZR1U,17.14.11,Asi se sintio Terremoto en iraq al bordo de ir...,MÚSICA & ENTRETENIMIENTO,10,2017-11-12T20:17:38.000Z,[none],129645,506,67,239,https://i.ytimg.com/vi/Q9kK6NWZR1U/default.jpg,False,False,False,Un fuerte sismo ha afectado en la noche de est...,MX
19,7D-swI6qNLM,17.14.11,HACKS CON SILICÓN CALIENTE,MaireWink,24,2017-11-13T18:00:01.000Z,[none],217025,26934,201,1277,https://i.ytimg.com/vi/7D-swI6qNLM/default.jpg,False,False,False,CANAL DE HISTORIAS:\nhttps://www.youtube.com/H...,MX
25,nEAMm3nGxpM,17.14.11,El valiente ve la muerte solo una vez - Teaser,Agencia Bengala,1,2017-11-13T13:32:23.000Z,[none],7127,37,3,13,https://i.ytimg.com/vi/nEAMm3nGxpM/default.jpg,False,False,False,"A lo largo de su vida, Alejo Garza Tamez ha cu...",MX
38,cgYhR-3QfhM,17.14.11,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,Las Ultimas de HOY,22,2017-11-12T21:00:01.000Z,[none],195613,929,238,92,https://i.ytimg.com/vi/cgYhR-3QfhM/default.jpg,False,False,False,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,MX
56,mevdRfjbwH4,17.14.11,Leslie mar vs Mayela Without you - la voz Méxi...,Pablo Zarate,29,2017-11-13T05:11:11.000Z,[none],15814,91,5,14,https://i.ytimg.com/vi/mevdRfjbwH4/default.jpg,False,False,False,NaN,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367560,WLeUt-jBE4Y,18.04.05,Aubrey Plaza Is More Famous Than Joe Biden - ...,Team Coco,23,2018-05-03T02:03:56.000Z,[none],265636,5326,103,696,https://i.ytimg.com/vi/WLeUt-jBE4Y/default.jpg,False,False,False,CONAN Highlight: The people of Delaware think ...,US
367812,13xFL17XmYU,18.05.05,Little Kid Runs in Slow Motion During Baseball...,RM Videos,24,2018-04-30T18:57:01.000Z,[none],188770,690,90,141,https://i.ytimg.com/vi/13xFL17XmYU/default.jpg,False,False,False,For licensing/usage please contact: licensing(...,US
368782,6mkLWGy6Y3k,18.10.05,Shawn Mendes: The Tour - Official Trailer,Shawn Mendes,10,2018-05-08T17:23:08.000Z,[none],332910,80118,232,5420,https://i.ytimg.com/vi/6mkLWGy6Y3k/default.jpg,False,False,False,For tickets & tour info head to: http://www.sh...,US
372640,bGW2eZGnznk,18.26.05,THE HAPPYTIME MURDERS Official Trailer (2018),Movie Trailers Source,1,2018-05-18T15:37:16.000Z,[none],312542,3186,450,557,https://i.ytimg.com/vi/bGW2eZGnznk/default.jpg,False,False,False,THE HAPPYTIME MURDERS Official Trailer Action...,GB
374389,1ce456Nnkt8,18.05.06,BABYMETAL - Distortion (OFFICIAL),BABYMETAL,10,2018-05-02T03:56:31.000Z,[none],2239777,125102,1091,10719,https://i.ytimg.com/vi/4nq0tT_SAD0/default.jpg,False,False,False,hey guys! i know this is a lil different than ...,US
374773,VGykknw9eCM,18.09.06,"Made Defiant: The Mixtape ft. Neymar Jr., Kane...",Beats by Dre,10,2018-06-07T07:01:06.000Z,[none],1029089,7382,483,703,https://i.ytimg.com/vi/VGykknw9eCM/default.jpg,False,False,False,"When your time comes, you have two choices. Yo...",US

### 3. For each channel, determine the total number of views

I computed total views per channel in a way that avoids double counting. Since the same video appears on multiple trending dates, I first took the maximum views for each (channel_title, video_id) pair, then I summed those values by channel.

In [7]:
# We take the max views per video within each channel, then sum per channel.
total_views_per_channel = (
    df_videos.groupby(["channel_title", "video_id"])["views"].max()
    .groupby("channel_title").sum()
    .sort_values(ascending=False)
)
total_views_per_channel

channel_title
T-Series             557665805
Ozuna                496503490
NickyJamTV           467892045
DrakeVEVO            364312023
Bad Bunny            357112379
                       ...
NavylittleMonster          365
Videostendencias           302
No Comment TV              284
Sport Life                 163
Alexander Redking          153
Name: views, Length: 37824, dtype: int64

### 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

I created an excluded dataframe with rows where both comments and ratings are disabled, or where the video is marked as error/removed. After saving those rows, I removed them from the main dataframe so later analyses use cleaner data.

In [8]:
excluded = df_videos[(df_videos["comments_disabled"] & df_videos["ratings_disabled"]) | df_videos["video_error_or_removed"]]
excluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
14,Dhhp8M5K3UI,17.14.11,Deleted video,Harrison,24,2017-11-13T04:44:51.000Z,"terremoto costa rica|""Primeras imagenes sismo ...",53265,194,41,90,https://i.ytimg.com/vi/7jmJtdqI6YE/default.jpg,False,False,True,Un sismo de magnitud 6.5 sacudió el domingo po...,MX
88,qxyJYWGf57k,17.14.11,Santa Misa del lunes 13 de noviembre de 2017 (...,Maria de Nazaret,27,2017-11-13T10:31:51.000Z,"Santa misa de hoy|""Santa Misa""|""Misa del dia d...",8010,0,0,0,https://i.ytimg.com/vi/qxyJYWGf57k/default.jpg,True,True,False,→ Suscríbete aquí y sigue la Misa diaria en es...,MX
597,gH777GgPKFY,17.16.11,Macrolibramiento de Guadalajara,SCTMexico,25,2017-11-15T16:30:01.000Z,[none],3710,0,0,0,https://i.ytimg.com/vi/gH777GgPKFY/default.jpg,True,True,False,NaN,MX
641,1sHrQoyTYi4,17.17.11,Cezür,ImagenTV,25,2017-11-17T02:24:16.000Z,[none],22273,0,0,0,https://i.ytimg.com/vi/1sHrQoyTYi4/default.jpg,True,True,False,NaN,MX
1026,kQAfFe6ykVA,17.19.11,Partido Querétaro vs Pumas,ImagenTV,25,2017-11-19T01:12:19.000Z,[none],94226,0,0,0,https://i.ytimg.com/vi/kQAfFe6ykVA/default.jpg,True,True,False,NaN,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368180,1Aoc-cd9eYs,18.07.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",672609,4916,197,1269,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368407,1Aoc-cd9eYs,18.08.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",412323,25441,208,952,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368613,1Aoc-cd9eYs,18.09.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",251857,6623,231,1120,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368830,1Aoc-cd9eYs,18.10.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",629055,30695,277,1033,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
369587,1Aoc-cd9eYs,18.14.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",1062499,32276,4594,5547,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US

In [9]:
df_videos = df_videos.drop(excluded.index)
df_videos

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

### 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

I added like_ratio = likes / dislikes. To avoid division by zero, I replaced dislikes = 0 with NaN. This keeps undefined ratios explicit instead of creating invalid infinite values.

In [10]:
# Replace dislikes == 0 with NaN to avoid division-by-zero when computing like_ratio (likes / dislikes)
import numpy as np
df_videos["like_ratio"] = df_videos["likes"] / df_videos["dislikes"].replace(0, np.nan) 

df_videos[["title", "likes", "dislikes", "like_ratio"]].head(10)

,title,likes,dislikes,like_ratio
0,Capítulo 12 | MasterChef 2017,4182,361,11.584488
1,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,271,174,1.557471
2,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,10105,266,37.988722
3,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,378,171,2.210526
4,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,57781,681,84.847283
5,Asi se sintio Terremoto en iraq al bordo de ir...,506,67,7.552239
6,La Resolana con el Capi | Programa 12 noviembr...,2277,69,33.000000
7,M6.7 Costa Rica Análisis de Terremotos en (((A...,7745,659,11.752656
8,7 Niños Famosos Que No Supieron Adaptarse a La...,20155,912,22.099781
9,TOP: Los 7 libros infantiles más perturbadores...,83582,2194,38.095716

In [11]:
#if needed: total of disabled ratings
df_videos[df_videos["dislikes"] == 0]["ratings_disabled"].value_counts()

ratings_disabled
True     4941
False    2446
Name: count, dtype: int64

In [12]:
#percentage
df_videos[df_videos["dislikes"] == 0]["ratings_disabled"].value_counts(normalize=True) * 100

ratings_disabled
True     66.887776
False    33.112224
Name: proportion, dtype: float64

In [13]:
# how many rows have like_ratio = NaN (number of videos that have number of dislikes = 0)
num_nan_ratio = df_videos["like_ratio"].isna().sum()
print("Rows with like_ratio NaN:", num_nan_ratio)

Rows with like_ratio NaN: 7387

### 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

I converted publish_time to datetime in UTC, then clustered times into 10-minute bins using floor rounding.

In [14]:
pt = pd.to_datetime(df_videos["publish_time"], utc=True, errors="coerce")
start = pt.dt.floor("10min")
df_videos["publish_interval"] = (
    start.dt.strftime("%H:%M") + " - " +
    (start + pd.Timedelta(minutes=10)).dt.strftime("%H:%M")
)

df_videos[["publish_time", "publish_interval"]]

                    publish_time publish_interval
0       2017-11-13T06:06:22.000Z    06:00 - 06:10
1       2017-11-13T05:11:58.000Z    05:10 - 05:20
2       2017-11-13T17:00:02.000Z    17:00 - 17:10
3       2017-11-13T03:47:10.000Z    03:40 - 03:50
4       2017-11-13T19:17:48.000Z    19:10 - 19:20
...                          ...              ...
375937  2018-05-18T13:00:04.000Z    13:00 - 13:10
375938  2018-05-18T01:00:06.000Z    01:00 - 01:10
375939  2018-05-18T17:34:22.000Z    17:30 - 17:40
375940  2018-05-17T17:00:04.000Z    17:00 - 17:10
375941  2018-05-17T17:09:38.000Z    17:00 - 17:10

[373322 rows x 2 columns]

### 7. For each interval, determine the number of videos, average number of likes and of dislikes.

I computed interval statistics: number of videos, average likes, and average dislikes. I kept two perspectives: one by unique videos per interval, and one by trending appearances (rows). The unique-video version avoids overweighting videos that appear many times; the row-based version measures exposure frequency.

In [15]:
# Unique Videos (Counting unique videos per interval)
interval_video_level = df_videos.groupby(["publish_interval", "video_id"], as_index=False).agg(
    likes_per_video = ("likes", "mean"),
    dislikes_per_video = ("dislikes", "mean")
)

interval_stats = interval_video_level.groupby("publish_interval").agg(
    number_of_videos = ("video_id", "count"),
    average_likes = ("likes_per_video", "mean"),
    average_dislikes = ("dislikes_per_video", "mean")
)

interval_stats.sort_index().head(50)

                  number_of_videos  average_likes  average_dislikes
publish_interval
00:00 - 00:10                 1373   10041.422428        701.002357
00:10 - 00:20                  744    6401.510242        362.832520
00:20 - 00:30                  648    6972.182017        565.884921
00:30 - 00:40                  836    6840.721385        277.028457
00:40 - 00:50                  634    7772.500219        407.839193
00:50 - 01:00                  674    6848.324745        440.885769
01:00 - 01:10                 1345    7447.585638        316.287541
01:10 - 01:20                  700    8509.674071        587.311111
01:20 - 01:30                  701    6261.162182        352.061734
01:30 - 01:40                  863    5461.944278        404.174082
01:40 - 01:50                  692    6612.080824        371.286484
01:50 - 02:00                  612    5294.781449        373.304659
02:00 - 02:10                 1258    5946.850445        320.938755
02:10 - 02:20                  745    5729.865215        279.803094
02:20 - 02:30                  703    5455.304822        290.824189
02:30 - 02:40                  985    4909.080539        234.182303
02:40 - 02:50                  723    6706.162354        269.185447
02:50 - 03:00                  762    5543.269925        248.956621
03:00 - 03:10                 1657    6376.545454        309.310189
03:10 - 03:20                  832    4671.158431        370.299597
03:20 - 03:30                  713    3684.487592        205.254417
03:30 - 03:40                  979    5882.532183        383.530490
03:40 - 03:50                  692    6127.169994        281.294458
03:50 - 04:00                  627    6310.085280        355.222345
04:00 - 04:10                 1279   20058.386269        935.368161
04:10 - 04:20                  595    5361.863822        360.187882
04:20 - 04:30                  641    6040.966407        343.684903
04:30 - 04:40                 1050   10427.869790        526.435317
04:40 - 04:50                  627    7648.922365        425.931047
04:50 - 05:00                  605    7433.896090        593.279175
05:00 - 05:10                 1559   20471.760160        851.548199
05:10 - 05:20                  608    3733.445745        276.138357
05:20 - 05:30                  630    5625.144319        399.787904
05:30 - 05:40                  874    7311.301462        741.210545
05:40 - 05:50                  653    4913.074719        334.403250
05:50 - 06:00                  559    4419.598037        413.890893
06:00 - 06:10                 1298    6046.785596        574.115139
06:10 - 06:20                  571    4591.849798        361.682158
06:20 - 06:30                  612    5703.562964        642.906383
06:30 - 06:40                  892    7565.605991        688.316945
06:40 - 06:50                  610    5164.351610        490.433305
06:50 - 07:00                  594    7874.486690        568.922187
07:00 - 07:10                 1721    7970.836696        601.963250
07:10 - 07:20                  656    5269.814644        387.015909
07:20 - 07:30                  698    4444.973030        587.162137
07:30 - 07:40                  996    6503.039831        483.091582
07:40 - 07:50                  673    4988.997081        440.325122
07:50 - 08:00                  677    6963.170262        442.547828
08:00 - 08:10                 2125    6198.321068        356.463125
08:10 - 08:20                  767    5982.851007        403.294174

In [16]:
# By Rows (Counting trending apperances)
interval_stats = df_videos.groupby("publish_interval").agg(
    number_of_videos = ("video_id", "count"),
    average_likes = ("likes", "mean"),
    average_dislikes = ("dislikes", "mean")
)

interval_stats.sort_index().head(50)

                  number_of_videos  average_likes  average_dislikes
publish_interval
00:00 - 00:10                 2897   61288.115637       3808.149465
00:10 - 00:20                 1509   22748.138502       1449.836315
00:20 - 00:30                 1241   21378.280419       1072.344883
00:30 - 00:40                 1614   36853.560719        955.890954
00:40 - 00:50                 1269   42198.623325       1909.301812
00:50 - 01:00                 1322   37474.858548       1582.246596
01:00 - 01:10                 2742   15980.817287        734.974471
01:10 - 01:20                 1389  105969.572354       5892.362131
01:20 - 01:30                 1515   24597.400000       1666.618482
01:30 - 01:40                 1667   13511.931614       5765.304739
01:40 - 01:50                 1455   26704.760825       1506.415808
01:50 - 02:00                 1336   21978.761228       2905.236527
02:00 - 02:10                 2611   14646.565684        706.158560
02:10 - 02:20                 1550   35160.013548       1376.310323
02:20 - 02:30                 1238    8995.954766        653.592892
02:30 - 02:40                 1916   11411.300104        527.685282
02:40 - 02:50                 1379   47577.461929       1485.940537
02:50 - 03:00                 1323   15237.818594        614.013605
03:00 - 03:10                 3203   20712.213238       1408.035904
03:10 - 03:20                 1545    9825.693851        758.133333
03:20 - 03:30                 1305    7261.118774        648.217625
03:30 - 03:40                 2148   38870.504190       1815.291434
03:40 - 03:50                 1367   66971.965618       2331.697879
03:50 - 04:00                 1267   32238.835043       1794.164957
04:00 - 04:10                 3969  219909.924666       9924.942303
04:10 - 04:20                 1057   25603.498581       1824.656575
04:20 - 04:30                 1404   17748.344017        769.876068
04:30 - 04:40                 2484   32197.496779       1387.707729
04:40 - 04:50                 1294   69740.134467       2515.231066
04:50 - 05:00                 1411   37883.815734       3235.178597
05:00 - 05:10                 5170  155422.913733       6023.747389
05:10 - 05:20                 1178    8263.010187        571.179966
05:20 - 05:30                 1348   17165.205490        942.781157
05:30 - 05:40                 1875   24377.230400       2035.173333
05:40 - 05:50                 1289   26235.209465       1710.182312
05:50 - 06:00                 1120   14916.527679        651.291071
06:00 - 06:10                 2432   14084.914062       1111.472862
06:10 - 06:20                 1088   13644.054228        636.314338
06:20 - 06:30                 1250   19853.352000       2213.316000
06:30 - 06:40                 1865   18335.142627       1147.692761
06:40 - 06:50                 1194   15885.597152        895.891960
06:50 - 07:00                 1271   27050.829268       1591.417781
07:00 - 07:10                 3521   28383.498722       1546.295655
07:10 - 07:20                 1115   10998.308520        650.420628
07:20 - 07:30                 1240    6798.712097        702.777419
07:30 - 07:40                 2125   16908.429176       1160.695529
07:40 - 07:50                 1188    8340.664983        650.955387
07:50 - 08:00                 1409   51233.770759       2160.019163
08:00 - 08:10                 4089   20478.445830       1015.778185
08:10 - 08:20                 1398   28434.268956        915.447067

### 8. For each tag, determine the number of videos. Notice that tags contains a string with several tags

Setup tag column in our dataframe first <br>
Split the string into array with '|' as the separator <br>

Explode dataframe so that each row wiill have one tag, it will duplicate rows with many tags. This is the approach because it is useful when grouping by tags.

In [17]:
df_videos_tags = df_videos.copy()

In [18]:
df_videos_tags["tags"] = df_videos_tags["tags"].str.split('|')

In [19]:
df_videos_tags = df_videos_tags[["video_id", "tags", "like_ratio", "country", "trending_date"]]

In [20]:
df_videos_tags_explode = df_videos_tags.explode('tags')

In [21]:
# clean dataset by removing all extra characters such as double quotations (")
df_videos_tags_explode["tags"] = (
    df_videos_tags_explode["tags"]
    .astype(str)
    .str.replace('"', '', regex=False)
    .str.strip()
    .str.lower()
)

In [22]:
df_videos_tags_explode = df_videos_tags_explode[
    (df_videos_tags_explode["tags"].str.strip() != "") &
    (~df_videos_tags_explode["tags"].str.strip().str.lower().isin(["[none]", "none", "nan", "null"]))
]

In [23]:
# Videos with no tags are excluded
df_videos_tags_explode.groupby(by="tags")['video_id'].nunique()

tags
! banii i-au luat mintile                          2
!!                                                 5
!! *me bloquea*                                    1
!!!                                                1
!!!!                                               2
                                                  ..
😥                                                  1
😭 #résistancelamaindesqueezie ❤️                   1
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية    1
🚀 smartpixel.com.ua                                1
🤝 zarbex zahlt schutzgeld!!!                       1
Name: video_id, Length: 767108, dtype: int64

### 9. Find the tags with the largest number of videos

In [24]:
df_videos_tags_explode[df_videos_tags_explode["tags"] != "[none]"].groupby(by="tags")['video_id'].nunique().sort_values(ascending=False).head(1)

tags
2018    5754
Name: video_id, dtype: int64

### 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [25]:
df_videos_tags_only = df_videos_tags_explode[(df_videos_tags_explode["tags"] != "[none]")]

In [26]:
pd.DataFrame(df_videos_tags_only.groupby(by=["tags","country"])["like_ratio"].mean())

                                                         like_ratio
tags                                            country
! banii i-au luat mintile                       DE         6.222739
!!                                              FR        12.452875
                                                MX        38.081559
!! *me bloquea*                                 MX        65.260870
!!!                                             MX        12.952381
...                                                             ...
😥                                               DE        26.384615
😭 #résistancelamaindesqueezie ❤️                FR        10.219048
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية FR         6.223873
🚀 smartpixel.com.ua                             RU         0.714286
🤝 zarbex zahlt schutzgeld!!!                    DE        13.989691

[998157 rows x 1 columns]

### 11. For each (trending_date, country) pair, the video with the largest number of views

In [27]:
# For each (trending_date, country) group, idxmax() returns the index of the row with the highest views (one row per group).
max_views = df_videos.groupby(["trending_date", "country"])["views"].idxmax()
max_views

trending_date  country
17.01.12       CA         297510
               DE          43850
               FR          84822
               GB         224216
               IN         125271
                           ...
18.31.05       JP         218185
               KR         291507
               MX          37680
               RU         197171
               US         373139
Name: views, Length: 1967, dtype: int64

In [41]:
df_videos_group = df_videos.loc[max_views]
print(df_videos_group)

           video_id trending_date  \
177131  6ZfuNTqbHE8    2017-12-01
81202   6ZfuNTqbHE8    2017-12-01
258884  3VbHg5fqBYw    2017-12-01
340613  TyHvyGVs42U    2017-12-01
43707   6ZfuNTqbHE8    2017-12-01
...             ...           ...
136722  aJOTlE1K90k    2018-05-31
171128  ntWSnDV0MYs    2018-05-31
37680   xTlNMmZKwpA    2018-05-31
252418  1nX0kF2UwDc    2018-05-31
334223  VYOjWnS4cMY    2018-05-31

                                                    title  \
177131  Marvel Studios' Avengers: Infinity War Officia...
81202   Marvel Studios' Avengers: Infinity War Officia...
258884               Avengers: Infinity War Trailer Tease
340613          Luis Fonsi, Demi Lovato - Échame La Culpa
43707   Marvel Studios' Avengers: Infinity War Officia...
...                                                   ...
136722              Maroon 5 - Girls Like You ft. Cardi B
171128                     [MV] AOA _ Bingle Bangle(빙글뱅글)
37680   Cardi B, Bad Bunny & J Balvin - I Like It [Off...
252418  [BadComedian] - Движение Вверх (Плагиат или ве...
334223  Childish Gambino - This Is America (Official V...

               channel_title  category_id              publish_time  \
177131  Marvel Entertainment           24  2017-11-29T13:26:24.000Z
81202   Marvel Entertainment           24  2017-11-29T13:26:24.000Z
258884  Marvel Entertainment           24  2017-11-28T17:09:22.000Z
340613         LuisFonsiVEVO           10  2017-11-17T05:00:01.000Z
43707   Marvel Entertainment           24  2017-11-29T13:26:24.000Z
...                      ...          ...                       ...
136722           Maroon5VEVO           10  2018-05-31T04:00:00.000Z
171128          1theK (원더케이)           10  2018-05-28T09:00:03.000Z
37680                Cardi B           10  2018-05-29T14:05:10.000Z
252418           BadComedian           23  2018-05-30T18:20:48.000Z
334223   ChildishGambinoVEVO           10  2018-05-06T04:00:07.000Z

                                                     tags      views    likes  \
177131  marvel|"comics"|"comic books"|"nerdy"|"geeky"|...   56367282  2157741
81202   marvel|"comics"|"comic books"|"nerdy"|"geeky"|...   56367282  2157737
258884  marvel"|"comics"|"comic books"|"nerdy"|"geeky"...    7281189   180808
340613  Luis|"Fonsi"|"Demi"|"Lovato"|"Échame"|"La"|"Cu...  143408235  2686169
43707   marvel|"comics"|"comic books"|"nerdy"|"geeky"|...   56367282  2157733
...                                                   ...        ...      ...
136722  Maroon|"Girls"|"Like"|"You"|"Interscope"|"Reco...    3057987   406732
171128  Kpop|"1theK"|"원더케이"|"loen"|"로엔"|"뮤비"|"티져"|"MV"...    4150448   186262
37680   Cardi B|"I Like It"|"Invasion of Privacy"|"Bad...   20723565  1018817
252418  BadComedian|"Евген"|"Bad"|"Comedian"|"Фильмы"|...    3125598   334685
334223  Childish Gambino|"Rap"|"This Is America"|"mcDJ...  217750076  4934188

        dislikes  ...  comments_disabled ratings_disabled  \
177131     34078  ...              False            False
81202      34077  ...              False            False
258884     19955  ...              False            False
340613    137938  ...              False            False
43707      34077  ...              False            False
...          ...  ...                ...              ...
136722      4521  ...              False            False
171128      9728  ...              False            False
37680      48091  ...              False            False
252418      7777  ...              False            False
334223    335462  ...              False            False

        video_error_or_removed  \
177131                   False
81202                    False
258884                   False
340613                   False
43707                    False
...                        ...
136722                   False
171128                   False
37680                    False
252418                   False
334223                   False

                                              description  country like_ratio  \
177131  There was an idea… Avengers: Infinity War. In ...       CA  63.317712
81202   There was an idea… Avengers: Infinity War. In ...       DE  63.319453
258884  Thank you to the best fans in the universe! Ma...       FR   9.060787
340613  “Échame La Culpa” disponible ya en todas las p...       GB  19.473742
43707   There was an idea… Avengers: Infinity War. In ...       IN  63.319336
...                                                   ...      ...        ...
136722  Girls Like You” is out now.http://smarturl.it/...       JP  89.965052
171128  [MV] AOA _ Bingle Bangle(빙글뱅글)*English subtitl...       KR  19.146998
37680   Cardi B, Bad Bunny & J Balvin - I Like It from...       MX  21.185191
252418  #BadComedian обзор фильма Движение Вверх, кото...       RU  43.035232
334223  “This is America” by Childish Gambino http://s...       US  14.708635

       publish_interval  year month  day
177131    13:20 - 13:30  2017    12    1
81202     13:20 - 13:30  2017    12    1
258884    17:00 - 17:10  2017    12    1
340613    05:00 - 05:10  2017    12    1
43707     13:20 - 13:30  2017    12    1
...                 ...   ...   ...  ...
136722    04:00 - 04:10  2018     5   31
171128    09:00 - 09:10  2018     5   31
37680     14:00 - 14:10  2018     5   31
252418    18:20 - 18:30  2018     5   31
334223    04:00 - 04:10  2018     5   31

[1967 rows x 22 columns]

In [29]:
# Sort columns, to display Country, Trending Date and then Views First.
priority_columns = ["trending_date","country", "views"]
other_columns = [col for col in df_videos.columns if col not in priority_columns]

df_videos_group[priority_columns + other_columns]

,trending_date,country,views,video_id,title,channel_title,category_id,publish_time,tags,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,like_ratio,publish_interval
297510,17.01.12,CA,56367282,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29T13:26:24.000Z,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",2157741,34078,303178,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an idea… Avengers: Infinity War. In ...,63.317712,13:20 - 13:30
43850,17.01.12,DE,56367282,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29T13:26:24.000Z,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",2157737,34077,303178,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an idea… Avengers: Infinity War. In ...,63.319453,13:20 - 13:30
84822,17.01.12,FR,7281189,3VbHg5fqBYw,Avengers: Infinity War Trailer Tease,Marvel Entertainment,24,2017-11-28T17:09:22.000Z,"marvel""|""comics""|""comic books""|""nerdy""|""geeky""...",180808,19955,21244,https://i.ytimg.com/vi/3VbHg5fqBYw/default.jpg,False,False,False,Thank you to the best fans in the universe! Ma...,9.060787,17:00 - 17:10
224216,17.01.12,GB,143408235,TyHvyGVs42U,"Luis Fonsi, Demi Lovato - Échame La Culpa",LuisFonsiVEVO,10,2017-11-17T05:00:01.000Z,"Luis|""Fonsi""|""Demi""|""Lovato""|""Échame""|""La""|""Cu...",2686169,137938,144217,https://i.ytimg.com/vi/TyHvyGVs42U/default.jpg,False,False,False,“Échame La Culpa” disponible ya en todas las p...,19.473742,05:00 - 05:10
125271,17.01.12,IN,56367282,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29T13:26:24.000Z,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",2157733,34077,303178,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an idea… Avengers: Infinity War. In ...,63.319336,13:20 - 13:30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218185,18.31.05,JP,3057987,aJOTlE1K90k,Maroon 5 - Girls Like You ft. Cardi B,Maroon5VEVO,10,2018-05-31T04:00:00.000Z,"Maroon|""Girls""|""Like""|""You""|""Interscope""|""Reco...",406732,4521,31301,https://i.ytimg.com/vi/aJOTlE1K90k/default.jpg,False,False,False,Girls Like You” is out now.http://smarturl.it/...,89.965052,04:00 - 04:10
291507,18.31.05,KR,4150448,ntWSnDV0MYs,[MV] AOA _ Bingle Bangle(빙글뱅글),1theK (원더케이),10,2018-05-28T09:00:03.000Z,"Kpop|""1theK""|""원더케이""|""loen""|""로엔""|""뮤비""|""티져""|""MV""...",186262,9728,15989,https://i.ytimg.com/vi/ntWSnDV0MYs/default.jpg,False,False,False,[MV] AOA _ Bingle Bangle(빙글뱅글)*English subtitl...,19.146998,09:00 - 09:10
37680,18.31.05,MX,20723565,xTlNMmZKwpA,"Cardi B, Bad Bunny & J Balvin - I Like It [Off...",Cardi B,10,2018-05-29T14:05:10.000Z,"Cardi B|""I Like It""|""Invasion of Privacy""|""Bad...",1018817,48091,68790,https://i.ytimg.com/vi/xTlNMmZKwpA/default.jpg,False,False,False,"Cardi B, Bad Bunny & J Balvin - I Like It from...",21.185191,14:00 - 14:10
197171,18.31.05,RU,3125598,1nX0kF2UwDc,[BadComedian] - Движение Вверх (Плагиат или ве...,BadComedian,23,2018-05-30T18:20:48.000Z,"BadComedian|""Евген""|""Bad""|""Comedian""|""Фильмы""|...",334685,7777,34556,https://i.ytimg.com/vi/1nX0kF2UwDc/default.jpg,False,False,False,"#BadComedian обзор фильма Движение Вверх, кото...",43.035232,18:20 - 18:30
373139,18.31.05,US,217750076,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06T04:00:07.000Z,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",4934188,335462,509799,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...,14.708635,04:00 - 04:10

### 12. Divide trending_date into three columns: year, month, day

In [30]:
df_videos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 373322 entries, 0 to 375941
Data columns (total 19 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   video_id                373322 non-null  object
 1   trending_date           373322 non-null  object
 2   title                   373322 non-null  object
 3   channel_title           373322 non-null  object
 4   category_id             373322 non-null  int64
 5   publish_time            373322 non-null  object
 6   tags                    373322 non-null  object
 7   views                   373322 non-null  int64
 8   likes                   373322 non-null  int64
 9   dislikes                373322 non-null  int64
 10  comment_count           373322 non-null  int64
 11  thumbnail_link          373322 non-null  object
 12  comments_disabled       373322 non-null  bool
 13  ratings_disabled        373322 non-null  bool
 14  video_error_or_removed  373322 non-null  bool
 15  description             354157 non-null  object
 16  country                 373322 non-null  object
 17  like_ratio              365935 non-null  float64
 18  publish_interval        373322 non-null  object
dtypes: bool(3), float64(1), int64(5), object(10)
memory usage: 57.6+ MB

In [31]:
df_videos['trending_date'] = pd.to_datetime(df_videos['trending_date'], format='%y.%d.%m')

df_videos['year'] = df_videos['trending_date'].dt.year
df_videos['month'] = df_videos['trending_date'].dt.month
df_videos['day'] = df_videos['trending_date'].dt.day

print(df_videos[['trending_date', 'year', 'month', 'day']].head())

  trending_date  year  month  day
0    2017-11-14  2017     11   14
1    2017-11-14  2017     11   14
2    2017-11-14  2017     11   14
3    2017-11-14  2017     11   14
4    2017-11-14  2017     11   14

### 13. For each (month, country) pair, the video with the largest number of views

In [32]:
max_views_indices = df_videos.groupby(['month', 'country'])['views'].idxmax()

df_max_views = df_videos.loc[max_views_indices]

df_max_views

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval,year,month,day
305326,LsoLEjrDogU,2018-01-09,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04T04:49:43.000Z,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",43067983,1717177,61567,...,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,CA,27.891192,04:40 - 04:50,2018,1,9
51500,LsoLEjrDogU,2018-01-08,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04T04:49:43.000Z,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",37728802,1629946,56305,...,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,DE,28.948513,04:40 - 04:50,2018,1,8
92423,LsoLEjrDogU,2018-01-08,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04T04:49:43.000Z,"Bruno Mars""|""Finesse""|""Cardi B""|""Finesse Remix...",37728802,1629948,56305,...,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,FR,28.948548,04:40 - 04:50,2018,1,8
233392,LsoLEjrDogU,2018-01-18,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04T04:49:43.000Z,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",90598955,2248693,93089,...,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,GB,24.156377,04:40 - 04:50,2018,1,18
134059,dfnCAmr569k,2018-01-18,"Taylor Swift - End Game ft. Ed Sheeran, Future",TaylorSwiftVEVO,10,2018-01-12T05:00:01.000Z,"Taylor|""Swift""|""End""|""Game""|""Big""|""Machine""|""Pop""",42019590,1804377,100033,...,False,False,False,Music video by Taylor Swift performing End Gam...,IN,18.037818,05:00 - 05:10,2018,1,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127423,FlsCjmMhFmw,2017-12-12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",125432237,2912710,1545017,...,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",IN,1.885228,17:50 - 18:00,2017,12,12
264401,FlsCjmMhFmw,2017-12-11,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",113876217,2811223,1470388,...,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",KR,1.911892,17:50 - 18:00,2017,12,11
5261,FlsCjmMhFmw,2017-12-10,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",100912384,2656698,1353667,...,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",MX,1.962593,17:50 - 18:00,2017,12,10
164200,FlsCjmMhFmw,2017-12-08,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",52611730,1891836,884967,...,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",RU,2.137748,17:50 - 18:00,2017,12,8
341174,FlsCjmMhFmw,2017-12-14,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",149376127,3093544,1643059,...,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",US,1.882795,17:50 - 18:00,2017,12,14

### 14. Read all json files with the video categories

In [33]:
json_folder = 'categories'
df_list = []

for file in os.listdir(json_folder):
    if file.endswith(".json"):
        country_code = file.split('_')[0] 
        
        with open(os.path.join(json_folder, file), 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        df_temp = pd.json_normalize(data['items'])
        df_temp['id'] = df_temp['id'].astype(int)
        df_temp['country'] = country_code
        df_list.append(df_temp)

df_categories = pd.concat(df_list, ignore_index=True)

df_categories

,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable,country
0,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True,FR
1,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True,FR
2,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True,FR
3,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True,FR
4,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True,FR
...,...,...,...,...,...,...,...
306,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/N1TrDFLRppxZgBowC...",40,UCBR8-60-B28hp2BmDPdntcQ,Sci-Fi/Fantasy,False,DE
307,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/7UMGi6zRySqXopr_r...",41,UCBR8-60-B28hp2BmDPdntcQ,Thriller,False,DE
308,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/RScXhi324h8usyIet...",42,UCBR8-60-B28hp2BmDPdntcQ,Shorts,False,DE
309,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiG...",43,UCBR8-60-B28hp2BmDPdntcQ,Shows,False,DE
310,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/x5NxSf5fz8hn4loSN...",44,UCBR8-60-B28hp2BmDPdntcQ,Trailers,False,DE

### 15. For each country, determine how many videos have a category that is not assignable

In [34]:
df_merged = pd.merge(df_videos, df_categories, left_on = ['country', 'category_id'], right_on = ['country', 'id'],how='left')
df_merged.shape
df_merged

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,publish_interval,year,month,day,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable
0,SbOwzAl9ZfQ,2017-11-14,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,...,06:00 - 06:10,2017,11,14,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/UVB9oxX2Bvqa_w_y3...",24.0,UCBR8-60-B28hp2BmDPdntcQ,Entertainment,True
1,klOV6Xh-DnI,2017-11-14,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,...,05:10 - 05:20,2017,11,14,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/xId8RX7vRN8rqkbYZ...",22.0,UCBR8-60-B28hp2BmDPdntcQ,People & Blogs,True
2,6L2ZF7Qzsbk,2017-11-14,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,...,17:00 - 17:10,2017,11,14,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/QiLK0ZIrFoORdk_g2...",25.0,UCBR8-60-B28hp2BmDPdntcQ,News & Politics,True
3,hcY52MFWMDM,2017-11-14,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,...,03:40 - 03:50,2017,11,14,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/QiLK0ZIrFoORdk_g2...",25.0,UCBR8-60-B28hp2BmDPdntcQ,News & Politics,True
4,_OXDcGPVAa4,2017-11-14,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,...,19:10 - 19:20,2017,11,14,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/r6Ck6Z0_L0rG37VJQ...",26.0,UCBR8-60-B28hp2BmDPdntcQ,Howto & Style,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373317,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,...,13:00 - 13:10,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/HwXKamM1Q20q9BN-o...",15.0,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True
373318,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,...,01:00 - 01:10,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/xId8RX7vRN8rqkbYZ...",22.0,UCBR8-60-B28hp2BmDPdntcQ,People & Blogs,True
373319,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,...,17:30 - 17:40,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/UVB9oxX2Bvqa_w_y3...",24.0,UCBR8-60-B28hp2BmDPdntcQ,Entertainment,True
373320,oV0zkMe1K8s,2018-06-14,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,...,17:00 - 17:10,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/Xy1mB4_yLrHy_BmKm...",1.0,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True
373321,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,17:00 - 17:10,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/WmA0qYEfjWsAoyJFS...",20.0,UCBR8-60-B28hp2BmDPdntcQ,Gaming,True

In [35]:
# Videos where category information is missing (assignable is NaN)
missing_info = df_merged[df_merged['snippet.assignable'].isna()]
missing_info[['video_id','category_id','country','snippet.assignable']]

           video_id  category_id country snippet.assignable
55      mevdRfjbwH4           29      MX                NaN
60      M4W-nrYGRYc           29      MX                NaN
232     Lz58Ch1VnR8           29      MX                NaN
251     YCQEo_2f5SU           29      MX                NaN
389     o6Qj8FgmgXU           29      MX                NaN
...             ...          ...     ...                ...
322449  p1DAEZNyJ8E           29      CA                NaN
322651  BqD0umu1mRA           29      CA                NaN
322682  p1DAEZNyJ8E           29      CA                NaN
323330  OxN0qnqaYx0           29      CA                NaN
324487  dGM_E8T1t_E           29      CA                NaN

[2684 rows x 4 columns]

In [36]:
#Missing categories in JSON files for each country
missing_categories_by_country = (
    df_merged[df_merged['snippet.assignable'].isna()]
    .groupby('country')
    ['category_id'].unique() 
    .reset_index(name='missing_category_id')
)

print(missing_categories_by_country)

  country missing_category_id
0      CA                [29]
1      DE                [29]
2      FR                [29]
3      GB                [29]
4      IN                [29]
5      JP                [29]
6      KR                [29]
7      MX                [29]
8      RU                [29]

In [37]:
#video count for each country where assignable is NaN
df_Nan_assignable = (
    df_merged[df_merged['snippet.assignable'].isna()]
    .groupby('country')
    ['video_id'].nunique()
    .reset_index(name='nan_assignable_count')
    .sort_values('nan_assignable_count', ascending=False)
)

print(df_Nan_assignable)

  country  nan_assignable_count
8      RU                  1313
7      MX                   211
1      DE                   192
6      KR                   118
2      FR                   103
0      CA                    50
4      IN                    48
5      JP                    13
3      GB                     6

In [38]:
# count of unique videos that are not assignable for each country, including those with NaN assignable
df_Nan_not_assignable = (df_merged[(df_merged['snippet.assignable'] == False) | (df_merged['snippet.assignable'].isna())]
    .groupby('country')
    ['video_id'].nunique()
    .reset_index(name='Nan_non_assignable_count')
    .sort_values('Nan_non_assignable_count', ascending = False) 
)

df_Nan_not_assignable

  country  Nan_non_assignable_count
8      RU                      1479
1      DE                       297
7      MX                       214
2      FR                       210
6      KR                       192
4      IN                       172
0      CA                       161
5      JP                        13
3      GB                         7
9      US                         4

In [39]:
# videos that are not assignable for each country (including countries with 0)
all_countries = sorted(df_videos['country'].unique())

df_non_assignable = (df_merged[df_merged['snippet.assignable'] == False]
    .groupby('country')['video_id'].nunique()
    .reindex(all_countries, fill_value=0)
    .reset_index(name='non_assignable_count')
    .sort_values('non_assignable_count', ascending=False)
)

df_non_assignable

  country  non_assignable_count
8      RU                   169
4      IN                   124
0      CA                   111
2      FR                   107
1      DE                   105
6      KR                    75
9      US                     4
7      MX                     3
3      GB                     1
5      JP                     0