# 2025-26 Project - Foundations of Computer Science

**Project by:**
- Herandez, Nicole Winy </br>
- Ortega, Azriel Matthew </br>
- Tibayan, Meryann Joy

In [19]:
# import libraries
import pandas as pd
import os
import json
import numpy as np

### 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [2]:
# read csv files with read_csv function from pandas
videos_folder = "videos"

df_cavideos = pd.read_csv(f"{videos_folder}/CAvideos.csv")
df_devideos = pd.read_csv(f"{videos_folder}/DEvideos.csv")
df_frvideos = pd.read_csv(f"{videos_folder}/FRvideos.csv")
df_gbvideos = pd.read_csv(f"{videos_folder}/GBvideos.csv")
df_invideos = pd.read_csv(f"{videos_folder}/INvideos.csv")
df_usvideos = pd.read_csv(f"{videos_folder}/USvideos.csv")

# After experimenting, it seems that using default encoding(utf-8) and using encoding errors
# to skip some bytes that cant be read is better than finding a specific encoding for each language
# However, this must be researched more for example: If this only a computer specific problem, or 
# there is a way to read everything properly without having to use encoding errors

df_jpvideos = pd.read_csv(f"{videos_folder}/JPvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_krvideos = pd.read_csv(f"{videos_folder}/KRvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_mxvideos = pd.read_csv(f"{videos_folder}/MXvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_ruvideos = pd.read_csv(f"{videos_folder}/RUvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")

They say it is hard to determine the correct encoding for each text file, especially if it is not utf-8 </br>
Reference https://community.dataquest.io/t/how-do-we-know-the-encoding-to-use-with-pd-read-csv-chardet-doesnt-help/467614/4 </br>

You have to do trial and error with all of the encodings to check which one works best. As for my testing 11/20/2025, utf-8 is best for all with the encoding_errors set to replace.

Here is the docs for checking all encodings : https://docs.python.org/3/library/codecs.html#standard-encodings

In [3]:
# Efficient code version (with concatenation process

# Import all csv files, read and compile them into one dataframe
# With the addition of adding a new column 'country' to determine from what csv file it came from

dataframe_lists = []
for file in os.listdir(videos_folder):
    if file[9:] == "csv":
        print(f"Reading {file}")
        df_temp = pd.read_csv(f"{videos_folder}/{file}", encoding_errors="replace")
        df_temp["country"] = file[:2] # add country column
        dataframe_lists.append(df_temp)

df_videos = pd.concat(dataframe_lists) # concatenate everything into one dataframe
df_videos = df_videos.reset_index(drop=True) # reset index

Reading MXvideos.csv
Reading DEvideos.csv
Reading FRvideos.csv
Reading INvideos.csv
Reading RUvideos.csv
Reading JPvideos.csv
Reading GBvideos.csv
Reading KRvideos.csv
Reading CAvideos.csv
Reading USvideos.csv

In [4]:
df_videos

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

### 2. Extract all videos that have no tag.

 I extracted videos with no tags by cleaning the tags column first: I handled nulls, converted values to strings, trimmed spaces, and normalized case. Then I filtered values like [none], none, empty string.

In [5]:
no_tag_videos = df_videos[df_videos["tags"].fillna("").astype(str).str.strip().str.lower().isin(["[none]", "none", "", "nan", "null"])]
no_tag_videos #print all videos that have tags [none]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
5,Q9kK6NWZR1U,17.14.11,Asi se sintio Terremoto en iraq al bordo de ir...,MÚSICA & ENTRETENIMIENTO,10,2017-11-12T20:17:38.000Z,[none],129645,506,67,239,https://i.ytimg.com/vi/Q9kK6NWZR1U/default.jpg,False,False,False,Un fuerte sismo ha afectado en la noche de est...,MX
19,7D-swI6qNLM,17.14.11,HACKS CON SILICÓN CALIENTE,MaireWink,24,2017-11-13T18:00:01.000Z,[none],217025,26934,201,1277,https://i.ytimg.com/vi/7D-swI6qNLM/default.jpg,False,False,False,CANAL DE HISTORIAS:\nhttps://www.youtube.com/H...,MX
25,nEAMm3nGxpM,17.14.11,El valiente ve la muerte solo una vez - Teaser,Agencia Bengala,1,2017-11-13T13:32:23.000Z,[none],7127,37,3,13,https://i.ytimg.com/vi/nEAMm3nGxpM/default.jpg,False,False,False,"A lo largo de su vida, Alejo Garza Tamez ha cu...",MX
38,cgYhR-3QfhM,17.14.11,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,Las Ultimas de HOY,22,2017-11-12T21:00:01.000Z,[none],195613,929,238,92,https://i.ytimg.com/vi/cgYhR-3QfhM/default.jpg,False,False,False,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,MX
56,mevdRfjbwH4,17.14.11,Leslie mar vs Mayela Without you - la voz Méxi...,Pablo Zarate,29,2017-11-13T05:11:11.000Z,[none],15814,91,5,14,https://i.ytimg.com/vi/mevdRfjbwH4/default.jpg,False,False,False,NaN,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375815,VGykknw9eCM,18.14.06,"Made Defiant: The Mixtape ft. Neymar Jr., Kane...",Beats by Dre,10,2018-06-07T07:01:06.000Z,[none],3577614,12318,1345,1414,https://i.ytimg.com/vi/VGykknw9eCM/default.jpg,False,False,False,"When your time comes, you have two choices. Yo...",US
375819,fAIX12F6958,18.14.06,Bumblebee (2018) - Official Teaser Trailer - P...,Paramount Pictures,1,2018-06-05T07:00:01.000Z,[none],19864779,228670,16420,46318,https://i.ytimg.com/vi/fAIX12F6958/default.jpg,False,False,False,Every adventure has a beginning. Watch the off...,US
375865,gS1DbvHHVH0,18.14.06,Going in to brain surgery,Simone Giertz,28,2018-05-30T14:22:13.000Z,[none],1635301,120791,1098,20711,https://i.ytimg.com/vi/gS1DbvHHVH0/default.jpg,False,False,False,We’ll post an update on Instagram and Twitter ...,US
375873,E4c7EE8_IX0,18.14.06,Weezer - Africa,weezer,10,2018-05-29T12:00:11.000Z,[none],4682557,115240,5069,9170,https://i.ytimg.com/vi/E4c7EE8_IX0/default.jpg,False,False,False,Stream + download the song: http://fanlink.to/...,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US

I also created a deduplicated version by video_id to count unique videos.

In [8]:
no_tag_videos_unici = no_tag_videos.drop_duplicates(subset=["video_id"])
no_tag_videos_unici #there are 23992 unique videos that have tags [none]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
5,Q9kK6NWZR1U,17.14.11,Asi se sintio Terremoto en iraq al bordo de ir...,MÚSICA & ENTRETENIMIENTO,10,2017-11-12T20:17:38.000Z,[none],129645,506,67,239,https://i.ytimg.com/vi/Q9kK6NWZR1U/default.jpg,False,False,False,Un fuerte sismo ha afectado en la noche de est...,MX
19,7D-swI6qNLM,17.14.11,HACKS CON SILICÓN CALIENTE,MaireWink,24,2017-11-13T18:00:01.000Z,[none],217025,26934,201,1277,https://i.ytimg.com/vi/7D-swI6qNLM/default.jpg,False,False,False,CANAL DE HISTORIAS:\nhttps://www.youtube.com/H...,MX
25,nEAMm3nGxpM,17.14.11,El valiente ve la muerte solo una vez - Teaser,Agencia Bengala,1,2017-11-13T13:32:23.000Z,[none],7127,37,3,13,https://i.ytimg.com/vi/nEAMm3nGxpM/default.jpg,False,False,False,"A lo largo de su vida, Alejo Garza Tamez ha cu...",MX
38,cgYhR-3QfhM,17.14.11,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,Las Ultimas de HOY,22,2017-11-12T21:00:01.000Z,[none],195613,929,238,92,https://i.ytimg.com/vi/cgYhR-3QfhM/default.jpg,False,False,False,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,MX
56,mevdRfjbwH4,17.14.11,Leslie mar vs Mayela Without you - la voz Méxi...,Pablo Zarate,29,2017-11-13T05:11:11.000Z,[none],15814,91,5,14,https://i.ytimg.com/vi/mevdRfjbwH4/default.jpg,False,False,False,NaN,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367560,WLeUt-jBE4Y,18.04.05,Aubrey Plaza Is More Famous Than Joe Biden - ...,Team Coco,23,2018-05-03T02:03:56.000Z,[none],265636,5326,103,696,https://i.ytimg.com/vi/WLeUt-jBE4Y/default.jpg,False,False,False,CONAN Highlight: The people of Delaware think ...,US
367812,13xFL17XmYU,18.05.05,Little Kid Runs in Slow Motion During Baseball...,RM Videos,24,2018-04-30T18:57:01.000Z,[none],188770,690,90,141,https://i.ytimg.com/vi/13xFL17XmYU/default.jpg,False,False,False,For licensing/usage please contact: licensing(...,US
368782,6mkLWGy6Y3k,18.10.05,Shawn Mendes: The Tour - Official Trailer,Shawn Mendes,10,2018-05-08T17:23:08.000Z,[none],332910,80118,232,5420,https://i.ytimg.com/vi/6mkLWGy6Y3k/default.jpg,False,False,False,For tickets & tour info head to: http://www.sh...,US
368876,4nq0tT_SAD0,18.10.05,singing the same song 6 years later..,Tiffany Day,10,2018-05-02T03:56:31.000Z,[none],2239777,125102,1091,10719,https://i.ytimg.com/vi/4nq0tT_SAD0/default.jpg,False,False,False,hey guys! i know this is a lil different than ...,US
374773,VGykknw9eCM,18.09.06,"Made Defiant: The Mixtape ft. Neymar Jr., Kane...",Beats by Dre,10,2018-06-07T07:01:06.000Z,[none],1029089,7382,483,703,https://i.ytimg.com/vi/VGykknw9eCM/default.jpg,False,False,False,"When your time comes, you have two choices. Yo...",US

### 3. For each channel, determine the total number of views

I computed total views per channel in a way that avoids double counting. Since the same video appears on multiple trending dates, I first took the maximum views for each (channel_title, video_id) pair, then I summed those values by channel.

In [9]:
# We take the max views per video within each channel, then sum per channel.
total_views_per_channel = (
    df_videos.groupby(["channel_title", "video_id"])["views"].max()
    .groupby("channel_title").sum()
    .sort_values(ascending=False)
)
total_views_per_channel

channel_title
T-Series             557665805
Ozuna                496503490
NickyJamTV           467892045
DrakeVEVO            364312023
Bad Bunny            357112379
                       ...
NavylittleMonster          365
Videostendencias           302
No Comment TV              284
Sport Life                 163
Alexander Redking          153
Name: views, Length: 37824, dtype: int64

### 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

I created an excluded dataframe with rows where both comments and ratings are disabled, or where the video is marked as error/removed. After saving those rows, I removed them from the main dataframe so later analyses use cleaner data.

In [10]:
excluded = df_videos[(df_videos["comments_disabled"] & df_videos["ratings_disabled"]) | df_videos["video_error_or_removed"]]
excluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
14,Dhhp8M5K3UI,17.14.11,Deleted video,Harrison,24,2017-11-13T04:44:51.000Z,"terremoto costa rica|""Primeras imagenes sismo ...",53265,194,41,90,https://i.ytimg.com/vi/7jmJtdqI6YE/default.jpg,False,False,True,Un sismo de magnitud 6.5 sacudió el domingo po...,MX
88,qxyJYWGf57k,17.14.11,Santa Misa del lunes 13 de noviembre de 2017 (...,Maria de Nazaret,27,2017-11-13T10:31:51.000Z,"Santa misa de hoy|""Santa Misa""|""Misa del dia d...",8010,0,0,0,https://i.ytimg.com/vi/qxyJYWGf57k/default.jpg,True,True,False,→ Suscríbete aquí y sigue la Misa diaria en es...,MX
597,gH777GgPKFY,17.16.11,Macrolibramiento de Guadalajara,SCTMexico,25,2017-11-15T16:30:01.000Z,[none],3710,0,0,0,https://i.ytimg.com/vi/gH777GgPKFY/default.jpg,True,True,False,NaN,MX
641,1sHrQoyTYi4,17.17.11,Cezür,ImagenTV,25,2017-11-17T02:24:16.000Z,[none],22273,0,0,0,https://i.ytimg.com/vi/1sHrQoyTYi4/default.jpg,True,True,False,NaN,MX
1026,kQAfFe6ykVA,17.19.11,Partido Querétaro vs Pumas,ImagenTV,25,2017-11-19T01:12:19.000Z,[none],94226,0,0,0,https://i.ytimg.com/vi/kQAfFe6ykVA/default.jpg,True,True,False,NaN,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368180,1Aoc-cd9eYs,18.07.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",672609,4916,197,1269,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368407,1Aoc-cd9eYs,18.08.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",412323,25441,208,952,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368613,1Aoc-cd9eYs,18.09.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",251857,6623,231,1120,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368830,1Aoc-cd9eYs,18.10.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",629055,30695,277,1033,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
369587,1Aoc-cd9eYs,18.14.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",1062499,32276,4594,5547,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US

In [11]:
df_videos = df_videos.drop(excluded.index)
df_videos

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

### 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

I added like_ratio = likes / dislikes. To avoid division by zero, I replaced dislikes = 0 with NaN. This keeps undefined ratios explicit instead of creating invalid infinite values.

In [20]:
# Replace dislikes == 0 with NaN to avoid division-by-zero when computing like_ratio (likes / dislikes)
df_videos["like_ratio"] = df_videos["likes"] / df_videos["dislikes"].replace(0, np.nan) 

df_videos[["title", "likes", "dislikes", "like_ratio"]].head(10)

,title,likes,dislikes,like_ratio
0,Capítulo 12 | MasterChef 2017,4182,361,11.584488
1,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,271,174,1.557471
2,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,10105,266,37.988722
3,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,378,171,2.210526
4,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,57781,681,84.847283
5,Asi se sintio Terremoto en iraq al bordo de ir...,506,67,7.552239
6,La Resolana con el Capi | Programa 12 noviembr...,2277,69,33.000000
7,M6.7 Costa Rica Análisis de Terremotos en (((A...,7745,659,11.752656
8,7 Niños Famosos Que No Supieron Adaptarse a La...,20155,912,22.099781
9,TOP: Los 7 libros infantiles más perturbadores...,83582,2194,38.095716

In [21]:
#if needed: total of disabled ratings
df_videos[df_videos["dislikes"] == 0]["ratings_disabled"].value_counts()

ratings_disabled
True     4941
False    2446
Name: count, dtype: int64

In [22]:
#percentage
df_videos[df_videos["dislikes"] == 0]["ratings_disabled"].value_counts(normalize=True) * 100

ratings_disabled
True     66.887776
False    33.112224
Name: proportion, dtype: float64

In [23]:
# how many rows have like_ratio = NaN (number of videos that have number of dislikes = 0)
num_nan_ratio = df_videos["like_ratio"].isna().sum()
print("Rows with like_ratio NaN:", num_nan_ratio)

Rows with like_ratio NaN: 7387

### 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

I converted publish_time to datetime in UTC, then clustered times into 10-minute bins using floor rounding.

In [ ]:
pt = pd.to_datetime(df_videos["publish_time"], utc=True, errors="coerce")
start = pt.dt.floor("10min")
df_videos["publish_interval"] = (
    start.dt.strftime("%H:%M") + " - " +
    (start + pd.Timedelta(minutes=10)).dt.strftime("%H:%M")
)

df_videos[["publish_time", "publish_interval"]]

### 7. For each interval, determine the number of videos, average number of likes and of dislikes.

I computed interval statistics: number of videos, average likes, and average dislikes. I kept two perspectives: one by unique videos per interval, and one by trending appearances (rows). The unique-video version avoids overweighting videos that appear many times; the row-based version measures exposure frequency.

In [ ]:
# Unique Videos (Counting unique videos per interval)
interval_video_level = df_videos.groupby(["publish_interval", "video_id"], as_index=False).agg(
    likes_per_video = ("likes", "mean"),
    dislikes_per_video = ("dislikes", "mean")
)

interval_stats = interval_video_level.groupby("publish_interval").agg(
    number_of_videos = ("video_id", "count"),
    average_likes = ("likes_per_video", "mean"),
    average_dislikes = ("dislikes_per_video", "mean")
)

interval_stats.sort_index().head(50)

In [ ]:
# By Rows (Counting trending apperances)
interval_stats = df_videos.groupby("publish_interval").agg(
    number_of_videos = ("video_id", "count"),
    average_likes = ("likes", "mean"),
    average_dislikes = ("dislikes", "mean")
)

interval_stats.sort_index().head(50)

### 8. For each tag, determine the number of videos. Notice that tags contains a string with several tags

Setup tag column in our dataframe first <br>
Split the string into array with '|' as the separator <br>

Explode dataframe so that each row wiill have one tag, it will duplicate rows with many tags. This is the approach because it is useful when grouping by tags.

In [ ]:
df_videos_tags = df_videos.copy()

In [ ]:
df_videos_tags["tags"] = df_videos_tags["tags"].str.split('|')

In [ ]:
df_videos_tags = df_videos_tags[["video_id", "tags", "like_ratio", "country", "trending_date"]]

In [ ]:
df_videos_tags_explode = df_videos_tags.explode('tags')

In [ ]:
# clean dataset by removing all extra characters such as double quotations (")
df_videos_tags_explode["tags"] = (
    df_videos_tags_explode["tags"]
    .astype(str)
    .str.replace('"', '', regex=False)
    .str.strip()
    .str.lower()
)

In [ ]:
df_videos_tags_explode = df_videos_tags_explode[
    (df_videos_tags_explode["tags"].str.strip() != "") &
    (~df_videos_tags_explode["tags"].str.strip().str.lower().isin(["[none]", "none", "nan", "null"]))
]

In [ ]:
# Videos with no tags are excluded
df_videos_tags_explode.groupby(by="tags")['video_id'].nunique()

### 9. Find the tags with the largest number of videos

In [ ]:
df_videos_tags_explode[df_videos_tags_explode["tags"] != "[none]"].groupby(by="tags")['video_id'].nunique().sort_values(ascending=False).head(1)

### 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [ ]:
df_videos_tags_only = df_videos_tags_explode[(df_videos_tags_explode["tags"] != "[none]")]

In [ ]:
pd.DataFrame(df_videos_tags_only.groupby(by=["tags","country"])["like_ratio"].mean())

### 11. For each (trending_date, country) pair, the video with the largest number of views

In [ ]:
# For each (trending_date, country) group, idxmax() returns the index of the row with the highest views (one row per group).
max_views = df_videos.groupby(["trending_date", "country"])["views"].idxmax()
max_views

In [ ]:
df_videos_group = df_videos.loc[max_views]
print(df_videos_group)

In [ ]:
# Sort columns, to display Country, Trending Date and then Views First.
priority_columns = ["trending_date","country", "views"]
other_columns = [col for col in df_videos.columns if col not in priority_columns]

df_videos_group[priority_columns + other_columns]

### 12. Divide trending_date into three columns: year, month, day

In [ ]:
df_videos.info()

In [ ]:
df_videos['trending_date'] = pd.to_datetime(df_videos['trending_date'], format='%y.%d.%m')

df_videos['year'] = df_videos['trending_date'].dt.year
df_videos['month'] = df_videos['trending_date'].dt.month
df_videos['day'] = df_videos['trending_date'].dt.day

print(df_videos[['trending_date', 'year', 'month', 'day']].head())

### 13. For each (month, country) pair, the video with the largest number of views

In [ ]:
max_views_indices = df_videos.groupby(['month', 'country'])['views'].idxmax()

df_max_views = df_videos.loc[max_views_indices]

df_max_views

### 14. Read all json files with the video categories

In [ ]:
json_folder = 'categories'
df_list = []

for file in os.listdir(json_folder):
    if file.endswith(".json"):
        country_code = file.split('_')[0] 
        
        with open(os.path.join(json_folder, file), 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        df_temp = pd.json_normalize(data['items'])
        df_temp['id'] = df_temp['id'].astype(int)
        df_temp['country'] = country_code
        df_list.append(df_temp)

df_categories = pd.concat(df_list, ignore_index=True)

df_categories

### 15. For each country, determine how many videos have a category that is not assignable

In [ ]:
df_merged = pd.merge(df_videos, df_categories, left_on = ['country', 'category_id'], right_on = ['country', 'id'],how='left')
df_merged.shape
df_merged

In [ ]:
# Videos where category information is missing (assignable is NaN)
missing_info = df_merged[df_merged['snippet.assignable'].isna()]
missing_info[['video_id','category_id','country','snippet.assignable']]

In [ ]:
#Missing categories in JSON files for each country
missing_categories_by_country = (
    df_merged[df_merged['snippet.assignable'].isna()]
    .groupby('country')
    ['category_id'].unique() 
    .reset_index(name='missing_category_id')
)

print(missing_categories_by_country)

In [ ]:
#video count for each country where assignable is NaN
df_Nan_assignable = (
    df_merged[df_merged['snippet.assignable'].isna()]
    .groupby('country')
    ['video_id'].nunique()
    .reset_index(name='nan_assignable_count')
    .sort_values('nan_assignable_count', ascending=False)
)

print(df_Nan_assignable)

In [ ]:
# count of unique videos that are not assignable for each country, including those with NaN assignable
df_Nan_not_assignable = (df_merged[(df_merged['snippet.assignable'] == False) | (df_merged['snippet.assignable'].isna())]
    .groupby('country')
    ['video_id'].nunique()
    .reset_index(name='Nan_non_assignable_count')
    .sort_values('Nan_non_assignable_count', ascending = False) 
)

df_Nan_not_assignable

In [ ]:
# videos that are not assignable for each country (including countries with 0)
all_countries = sorted(df_videos['country'].unique())

df_non_assignable = (df_merged[df_merged['snippet.assignable'] == False]
    .groupby('country')['video_id'].nunique()
    .reindex(all_countries, fill_value=0)
    .reset_index(name='non_assignable_count')
    .sort_values('non_assignable_count', ascending=False)
)

df_non_assignable